from __future__ import annotations

import os
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
SRC_ROOT = PROJECT_ROOT / "src"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from short_term_edge.phase6d import Phase6DConfig, run_phase6d_search, write_phase6d_specs  # noqa: E402


def main() -> None:
    output_dir = PROJECT_ROOT / "outputs"
    report_dir = PROJECT_ROOT / "reports"
    output_dir.mkdir(parents=True, exist_ok=True)
    report_dir.mkdir(parents=True, exist_ok=True)

    max_new = int(os.environ.get("PHASE6D_MAX_NEW_SPECS", "6"))
    config = Phase6DConfig(symbol="MNQ", max_specs=24, min_specs=12, batch_size=1, max_new_specs_per_run=max_new)
    results_path = output_dir / "phase6d_side_only_results.csv"
    specs_path = output_dir / "phase6d_candidate_specs.json"
    report_path = report_dir / "phase6d_side_only_search_report.md"

    result = run_phase6d_search(PROJECT_ROOT, config, checkpoint_path=results_path)
    result.search_results.to_csv(results_path, index=False)
    write_phase6d_specs(result.specs, specs_path)
    report_path.write_text(_report(config, result, results_path, specs_path, report_path), encoding="utf-8")

    print("Phase 6D side-only search complete.")
    print(f"Search results: {results_path}")
    print(f"Candidate specs: {specs_path}")
    print(f"Report: {report_path}")
    print(f"Rows scored: {len(result.search_results)} / {len(result.specs)} selected specs")
    if not result.search_results.empty:
        top = result.search_results.iloc[0]
        print(f"Top candidate: {top['candidate_id']} side={top['side_filter']} score={top['phase6d_score']} label={top['phase6d_label']} net={top['net_pnl']:.2f}")


def _report(config: Phase6DConfig, result, results_path: Path, specs_path: Path, report_path: Path) -> str:
    label_counts = result.search_results["phase6d_label"].value_counts().to_dict() if not result.search_results.empty and "phase6d_label" in result.search_results else {}
    lines = [
        "# Phase 6D Long/Short-Only Search Report",
        "",
        "Generated by: `./.venv/Scripts/python.exe scripts/run_phase6d_side_only_search.py`",
        "",
        "## Scope And Guardrails",
        "",
        "- Research/simulation only. No live trading, broker adapters, API-key storage, webhooks, order routing, or automated execution were added.",
        "- Phase 6D remains MNQ-only and uses local CSV-derived data under `data/raw`.",
        "- Candidate specs are deterministic and serializable; no LLM-driven trade entries/exits/sizing were added.",
        "- Search tests long-only and short-only variants of the strongest Phase 6B reduced-ambiguity bases.",
        "",
        "## Configuration",
        "",
        f"- Symbol: `{config.symbol}`",
        f"- Candidate cap: `{config.max_specs}` specs; selected `{len(result.specs)}` specs",
        f"- Checkpoint batch size: `{config.batch_size}` specs; existing candidate IDs are skipped on resume",
        f"- Max new specs this invocation: `{config.max_new_specs_per_run}` (set `PHASE6D_MAX_NEW_SPECS` to adjust bounded batches)",
        f"- Complete MNQ sessions: `{len(result.complete_sessions)}`" if result.complete_sessions else "- Complete MNQ sessions: not reloaded during checkpoint-only refresh",
        f"- Label counts: `{label_counts}`",
        "",
        "## Outputs",
        "",
        f"- Search results: `{results_path}`",
        f"- Candidate specs: `{specs_path}`",
        f"- Report: `{report_path}`",
        "",
        "## Top Ranked Results",
        "",
        "| Rank | Candidate | Family | Side | TF | Label | Score | Net PnL | 4-Tick Slip | Trades | Active % | Max DD | Day Conc. | Trade Conc. | Notes |",
        "| ---: | --- | --- | --- | ---: | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- |",
    ]
    if not result.search_results.empty:
        for _, row in result.search_results.head(15).iterrows():
            lines.append(
                f"| {int(row['phase6d_rank'])} | `{row['candidate_id']}` | {row['family']} | {row['side_filter']} | {int(row['timeframe'])} | {row['phase6d_label']} | {row['phase6d_score']:.2f} | ${row['net_pnl']:.2f} | ${row['slippage_4_ticks_net_pnl']:.2f} | {int(row['trades'])} | {row['active_session_pct'] * 100:.1f}% | ${row['max_drawdown']:.2f} | {row['best_day_concentration'] * 100:.1f}% | {row['best_trade_concentration'] * 100:.1f}% | {row['phase6d_notes']} |"
            )
    lines.extend(
        [
            "",
            "## Interpretation",
            "",
            "- `side_only_prefilter_survivor` means a directional-only candidate survived cheap full-history gates and needs deep walk-forward validation before paper-trading consideration.",
            "- `side_only_watchlist` means the directional-only candidate passed core gates but had weak validation/holdout split behavior.",
            "- `rejected` means it failed one or more full-history gates.",
            "",
            "## Repro Command",
            "",
            "```bash",
            "PHASE6D_MAX_NEW_SPECS=6 ./.venv/Scripts/python.exe scripts/run_phase6d_side_only_search.py",
            "```",
            "",
        ]
    )
    return "\n".join(lines)


if __name__ == "__main__":
    main()
