from __future__ import annotations

import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
SRC_ROOT = PROJECT_ROOT / "src"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from short_term_edge.phase5f import Phase5FConfig, run_phase5f_search, write_phase5f_specs  # noqa: E402
from short_term_edge.walk_forward import WalkForwardConfig  # noqa: E402


def main() -> None:
    output_dir = PROJECT_ROOT / "outputs"
    report_dir = PROJECT_ROOT / "reports"
    output_dir.mkdir(parents=True, exist_ok=True)
    report_dir.mkdir(parents=True, exist_ok=True)

    config = Phase5FConfig(
        symbols=("MNQ",),
        candidates_per_symbol=3,
        seed=606,
        timeframes=(1, 3, 5),
        opening_range_minutes=(30,),
        walk_forward=WalkForwardConfig(train_sessions=120, validation_sessions=30, test_sessions=30, step_sessions=360, min_folds=2, max_candidates=1),
    )
    result = run_phase5f_search(PROJECT_ROOT, config)

    results_path = output_dir / "phase5f_walk_forward_search_results.csv"
    fold_path = output_dir / "phase5f_walk_forward_fold_results.csv"
    specs_path = output_dir / "phase5f_candidate_specs.json"
    report_path = report_dir / "phase5f_walk_forward_search_report.md"
    result.search_results.to_csv(results_path, index=False)
    result.fold_results.to_csv(fold_path, index=False)
    write_phase5f_specs(result.specs, specs_path)
    report_path.write_text(_report(result, config, results_path, fold_path, specs_path), encoding="utf-8")

    print("Phase 5F walk-forward-aware deterministic search complete.")
    print(f"Search results: {results_path}")
    print(f"Fold results: {fold_path}")
    print(f"Candidate specs: {specs_path}")
    print(f"Report: {report_path}")
    print(f"Candidates: {len(result.specs)}")
    print(f"Folds: {len(result.folds)}")
    if not result.search_results.empty:
        top = result.search_results.iloc[0]
        print(f"Top candidate: {top['candidate_id']} score={top['phase5f_score']} label={top['phase5f_label']} test_net={top['test_net_pnl']:.2f}")


def _report(result, config: Phase5FConfig, results_path: Path, fold_path: Path, specs_path: Path) -> str:
    ranked = result.search_results
    lines = [
        "# Phase 5F Walk-Forward-Aware Search Report",
        "",
        "Generated by: `./.venv/Scripts/python.exe scripts/run_phase5f_walk_forward_search.py`",
        "",
        "## Scope And Guardrails",
        "",
        "- Research/simulation only. No live trading, broker adapters, API-key storage, webhooks, order routing, or automated execution were added.",
        "- Phase 5F searches deterministic serializable strategy specs by walk-forward stability, not recent-window PnL.",
        "- Source data is local only under `data/raw`; no data was downloaded.",
        "- This first bounded run focuses on MNQ opening-range-failure variants before expanding to MGC.",
        "",
        "## Search Configuration",
        "",
        f"- Symbols: `{', '.join(config.symbols)}`",
        f"- Candidates per symbol: `{config.candidates_per_symbol}`",
        f"- Signal timeframes checked: `{', '.join(str(tf) + 'm' for tf in config.timeframes)}`",
        f"- Opening range windows checked: `{', '.join(str(x) + 'm' for x in config.opening_range_minutes)}`",
        f"- Walk-forward train/validation/test: `{config.walk_forward.train_sessions}/{config.walk_forward.validation_sessions}/{config.walk_forward.test_sessions}` sessions",
        f"- Step sessions: `{config.walk_forward.step_sessions}`",
        f"- Folds: `{len(result.folds)}`",
        "",
        "## Outputs",
        "",
        f"- Search results: `{results_path}`",
        f"- Fold-level results: `{fold_path}`",
        f"- Candidate specs: `{specs_path}`",
        f"- Report: `{PROJECT_ROOT / 'reports' / 'phase5f_walk_forward_search_report.md'}`",
        "",
        "## Top Walk-Forward Search Results",
        "",
    ]
    if ranked.empty:
        lines.append("- No candidates were evaluated.")
    else:
        lines.extend(
            [
                "| Rank | Candidate | Symbol | TF | Label | Score | Test Net | Test 4-Tick Slip | Positive Test Folds | Trades | Active % | Notes |",
                "| ---: | --- | --- | ---: | --- | ---: | ---: | ---: | ---: | ---: | ---: | --- |",
            ]
        )
        for _, row in ranked.iterrows():
            lines.append(
                f"| {int(row['phase5f_rank'])} | `{row['candidate_id']}` | {row['instrument']} | {int(row['timeframe'])}m | {row['phase5f_label']} | {row['phase5f_score']:.2f} | ${row['test_net_pnl']:.2f} | ${row['test_slippage_4_ticks_net_pnl']:.2f} | {int(row['test_positive_folds'])}/{int(row['folds'])} | {int(row['test_trades'])} | {row['test_active_session_pct'] * 100:.1f}% | {row['phase5f_notes']} |"
            )
        lines.extend(["", "## Readout", "", f"- Label counts: `{ranked['phase5f_label'].value_counts().to_dict()}`"])
    lines.extend(
        [
            "",
            "## Repro Command",
            "",
            "```bash",
            "./.venv/Scripts/python.exe scripts/run_phase5f_walk_forward_search.py",
            "```",
            "",
        ]
    )
    return "\n".join(lines)


if __name__ == "__main__":
    main()
