from __future__ import annotations

import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
SRC_ROOT = PROJECT_ROOT / "src"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from short_term_edge.phase5k import Phase5KConfig, run_phase5k_search, write_phase5k_specs  # noqa: E402
from short_term_edge.walk_forward import WalkForwardConfig  # noqa: E402


def main() -> None:
    output_dir = PROJECT_ROOT / "outputs"
    report_dir = PROJECT_ROOT / "reports"
    output_dir.mkdir(parents=True, exist_ok=True)
    report_dir.mkdir(parents=True, exist_ok=True)

    config = Phase5KConfig(
        symbol="MNQ",
        max_specs=6,
        timeframes=(1, 3, 5),
        walk_forward=WalkForwardConfig(train_sessions=60, validation_sessions=20, test_sessions=20, step_sessions=10_000, min_folds=1, max_candidates=1),
    )
    result = run_phase5k_search(PROJECT_ROOT, config)

    fold_path = output_dir / "phase5k_vwap_focus_fold_results.csv"
    results_path = output_dir / "phase5k_vwap_focus_results.csv"
    specs_path = output_dir / "phase5k_candidate_specs.json"
    report_path = report_dir / "phase5k_vwap_focus_report.md"

    result.fold_results.to_csv(fold_path, index=False)
    result.search_results.to_csv(results_path, index=False)
    write_phase5k_specs(result.specs, specs_path)
    report_path.write_text(_report(config, result, fold_path, results_path, specs_path, report_path), encoding="utf-8")

    print("Phase 5K VWAP-focused deterministic search complete.")
    print(f"Fold results: {fold_path}")
    print(f"Search results: {results_path}")
    print(f"Candidate specs: {specs_path}")
    print(f"Report: {report_path}")
    print(f"Candidates evaluated: {len(result.search_results)}")
    if not result.search_results.empty:
        top = result.search_results.iloc[0]
        print(f"Top candidate: {top['candidate_id']} score={top['phase5k_score']} label={top['phase5k_label']} test_net={top['test_net_pnl']:.2f}")


def _report(config: Phase5KConfig, result, fold_path: Path, results_path: Path, specs_path: Path, report_path: Path) -> str:
    lines = [
        "# Phase 5K VWAP-Focused Search Report",
        "",
        "Generated by: `./.venv/Scripts/python.exe scripts/run_phase5k_vwap_focus_search.py`",
        "",
        "## Scope And Guardrails",
        "",
        "- Research/simulation only. No live trading, broker adapters, API-key storage, webhooks, order routing, or automated execution were added.",
        "- Phase 5K expands only deterministic VWAP reclaim/rejection variants after Phase 5J found VWAP closest to concentration thresholds.",
        "- This run is MNQ-only and bounded for interactive runtime.",
        "- Source data is local only under `data/raw`; no data was downloaded.",
        "",
        "## Search Configuration",
        "",
        f"- Symbol: `{config.symbol}`",
        f"- Candidate specs: `{config.max_specs}`",
        f"- Timeframes: `{', '.join(str(tf) + 'm' for tf in config.timeframes)}`",
        f"- Walk-forward train/validation/test: `{config.walk_forward.train_sessions}/{config.walk_forward.validation_sessions}/{config.walk_forward.test_sessions}` sessions",
        f"- Step sessions: `{config.walk_forward.step_sessions}`",
        "",
        "## Outputs",
        "",
        f"- Fold results: `{fold_path}`",
        f"- Search results: `{results_path}`",
        f"- Candidate specs: `{specs_path}`",
        f"- Report: `{report_path}`",
        "",
        "## Top Results",
        "",
    ]
    if result.search_results.empty:
        lines.append("No results were produced.")
    else:
        lines.extend([
            "| Rank | Candidate | TF | Label | Score | Test Net | 4-Tick Slip | Positive Folds | Active % | Day Conc. | Trade Conc. | Notes |",
            "| ---: | --- | ---: | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- |",
        ])
        for _, row in result.search_results.head(12).iterrows():
            lines.append(
                f"| {int(row['phase5k_rank'])} | `{row['candidate_id']}` | {int(row['timeframe'])} | {row['phase5k_label']} | {row['phase5k_score']:.2f} | ${row['test_net_pnl']:.2f} | ${row['test_slippage_4_ticks_net_pnl']:.2f} | {int(row['test_positive_folds'])}/{int(row['folds'])} | {row['test_active_session_pct'] * 100:.1f}% | {row['test_best_day_concentration'] * 100:.1f}% | {row['test_best_trade_concentration'] * 100:.1f}% | {row['phase5k_notes']} |"
            )
        lines.extend(["", "## Readout", "", f"- Label counts: `{result.search_results['phase5k_label'].value_counts().to_dict()}`"])
    lines.extend([
        "",
        "## Interpretation",
        "",
        "- `vwap_research_candidate` means a VWAP variant passed slippage/positive-fold checks and current concentration thresholds.",
        "- `watchlist_concentrated` means profitable but still too concentrated for paper-test promotion.",
        "- `rejected` means the variant failed fold or slippage survival.",
        "",
        "## Repro Command",
        "",
        "```bash",
        "./.venv/Scripts/python.exe scripts/run_phase5k_vwap_focus_search.py",
        "```",
        "",
    ])
    return "\n".join(lines)


if __name__ == "__main__":
    main()
