from __future__ import annotations

import os
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
SRC_ROOT = PROJECT_ROOT / "src"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from short_term_edge.phase7b import Phase7BConfig, run_phase7b_combo_reproduction, write_phase7b_combos  # noqa: E402


def main() -> None:
    output_dir = PROJECT_ROOT / "outputs"
    report_dir = PROJECT_ROOT / "reports"
    output_dir.mkdir(parents=True, exist_ok=True)
    report_dir.mkdir(parents=True, exist_ok=True)

    max_new = int(os.environ.get("PHASE7B_MAX_NEW_COMBOS", "2"))
    config = Phase7BConfig(symbol="MGC", max_combos=4, min_combos=4, max_new_combos_per_run=max_new, timeframes=(1,))
    results_path = output_dir / "phase7b_mgc_combo_results.csv"
    combos_path = output_dir / "phase7b_combo_specs.json"
    trade_log_path = output_dir / "phase7b_mgc_combo_trades.csv"
    report_path = report_dir / "phase7b_mgc_combo_report.md"

    result = run_phase7b_combo_reproduction(PROJECT_ROOT, config, checkpoint_path=results_path, trade_log_path=trade_log_path)
    result.combo_results.to_csv(results_path, index=False)
    write_phase7b_combos(result.combos, combos_path)
    result.trade_log.to_csv(trade_log_path, index=False)
    report_path.write_text(_render_report(config, result, results_path, combos_path, trade_log_path, report_path), encoding="utf-8")

    print("Phase 7B MGC combo/risk-gated reproduction complete.")
    print(f"Search results: {results_path}")
    print(f"Combo specs: {combos_path}")
    print(f"Trade log: {trade_log_path}")
    print(f"Report: {report_path}")
    print(f"Rows scored: {len(result.combo_results)} / {len(result.combos)} selected combos")
    if not result.combo_results.empty:
        top = result.combo_results.iloc[0]
        print(
            f"Top combo: {top['combo_id']} score={top['phase7b_score']} "
            f"label={top['phase7b_label']} net={top['net_pnl']:.2f} slip4={top['slippage_4_ticks_net_pnl']:.2f}"
        )


def _render_report(config: Phase7BConfig, result, results_path: Path, combos_path: Path, trade_log_path: Path, report_path: Path) -> str:
    label_counts = result.combo_results["phase7b_label"].value_counts().to_dict() if not result.combo_results.empty else {}
    lines = [
        "# Phase 7B MGC Combo / Risk-Gated Reproduction Report",
        "",
        "Generated by: `./.venv/Scripts/python.exe scripts/run_phase7b_mgc_combo_reproduction.py`",
        "",
        "## Scope And Guardrails",
        "",
        "- Research/simulation only. No live trading, broker adapters, API-key storage, webhooks, order routing, or automated execution were added.",
        "- Phase 7B is MGC-only and uses local CSV-derived data under `data/raw`.",
        "- This tests the older project's combo/risk-gated shape under current stricter validation rather than loosening acceptance criteria.",
        "- Candidate combos are deterministic and serializable; no LLM-driven trade entries/exits/sizing were added.",
        "",
        "## Combo Structure",
        "",
        "- Required legs: `vwap_pullback_continuation` short-only + `opening_drive_continuation`.",
        "- Optional leg in some combos: `opening_range_breakout`.",
        "- Account-level gates: max completed trades/day, daily loss lockout, daily profit lockout, one-open-position sequencing, and component priority ordering.",
        "",
        "## Configuration",
        "",
        f"- Symbol: `{config.symbol}`",
        f"- Combo cap: `{config.max_combos}` combos; selected `{len(result.combos)}` combos",
        f"- Timeframes: `{config.timeframes}`",
        f"- Max new combos this invocation: `{config.max_new_combos_per_run}` (set `PHASE7B_MAX_NEW_COMBOS` to adjust bounded batches)",
        f"- Complete MGC sessions: `{len(result.complete_sessions)}`" if result.complete_sessions else "- Complete MGC sessions: not reloaded during checkpoint-only refresh",
        f"- Label counts: `{label_counts}`",
        "",
        "## Outputs",
        "",
        f"- Search results: `{results_path}`",
        f"- Combo specs: `{combos_path}`",
        f"- Trade log: `{trade_log_path}`",
        f"- Report: `{report_path}`",
        "",
        "## Top Ranked Results",
        "",
        "| Rank | Combo | Label | Score | Net PnL | 4-Tick Slip | Trades | Active % | Max DD | Day Conc. | Trade Conc. | Components | Notes |",
        "| ---: | --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- | --- |",
    ]
    if not result.combo_results.empty:
        for _, row in result.combo_results.head(12).iterrows():
            lines.append(
                f"| {int(row['phase7b_rank'])} | `{row['combo_id']}` | {row['phase7b_label']} | {row['phase7b_score']:.2f} | ${row['net_pnl']:.2f} | ${row['slippage_4_ticks_net_pnl']:.2f} | {int(row['trades'])} | {row['active_session_pct'] * 100:.1f}% | ${row['max_drawdown']:.2f} | {row['best_day_concentration'] * 100:.1f}% | {row['best_trade_concentration'] * 100:.1f}% | `{row.get('component_trade_counts', '{}')}` | {row['phase7b_notes']} |"
            )
    lines.extend(
        [
            "",
            "## Interpretation",
            "",
            "- `mgc_combo_prefilter_survivor` means a risk-gated combo survived cheap full-history gates and needs walk-forward validation before paper-test consideration.",
            "- `mgc_combo_watchlist` means core gates passed but validation/holdout split behavior was weak.",
            "- `rejected` means the old-project combo structure did not transfer under current assumptions for that parameter set.",
            "",
            "## Repro Command",
            "",
            "```bash",
            "PHASE7B_MAX_NEW_COMBOS=2 ./.venv/Scripts/python.exe scripts/run_phase7b_mgc_combo_reproduction.py",
            "```",
            "",
        ]
    )
    return "\n".join(lines)


if __name__ == "__main__":
    main()
