from __future__ import annotations

import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
SRC_ROOT = PROJECT_ROOT / "src"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from short_term_edge.concentration import build_phase5f_fold_pnl, summarize_phase5f_fold_concentration  # noqa: E402


def main() -> None:
    output_dir = PROJECT_ROOT / "outputs"
    report_dir = PROJECT_ROOT / "reports"
    output_dir.mkdir(parents=True, exist_ok=True)
    report_dir.mkdir(parents=True, exist_ok=True)

    fold_pnl = build_phase5f_fold_pnl(PROJECT_ROOT)
    summary = summarize_phase5f_fold_concentration(PROJECT_ROOT)

    fold_path = output_dir / "phase5g_candidate_fold_pnl.csv"
    summary_path = output_dir / "phase5g_concentration_summary.csv"
    report_path = report_dir / "phase5g_concentration_diagnostics_report.md"

    fold_pnl.to_csv(fold_path, index=False)
    summary.to_csv(summary_path, index=False)
    report_path.write_text(_report(summary, fold_path, summary_path), encoding="utf-8")

    print("Phase 5G concentration diagnostics complete.")
    print(f"Fold PnL: {fold_path}")
    print(f"Summary: {summary_path}")
    print(f"Report: {report_path}")
    print(f"Candidates: {summary['candidate_id'].nunique() if not summary.empty else 0}")
    if not summary.empty:
        print(f"Labels: {summary['concentration_label'].value_counts().to_dict()}")


def _report(summary, fold_path: Path, summary_path: Path) -> str:
    lines = [
        "# Phase 5G Concentration Diagnostics Report",
        "",
        "Generated by: `./.venv/Scripts/python.exe scripts/run_phase5g_concentration_diagnostics.py`",
        "",
        "## Scope And Guardrails",
        "",
        "- Research/simulation only. No live trading, broker adapters, API-key storage, webhooks, order routing, or automated execution were added.",
        "- Diagnostics analyze existing Phase 5F walk-forward test-fold metrics; they do not create live signals.",
        "- Source data is local only under `data/raw`; no data was downloaded.",
        "- This is a fast fold-level concentration screen before slower trade-level/day-week-month attribution.",
        "",
        "## Outputs",
        "",
        f"- Fold PnL: `{fold_path}`",
        f"- Summary: `{summary_path}`",
        f"- Report: `{PROJECT_ROOT / 'reports' / 'phase5g_concentration_diagnostics_report.md'}`",
        "",
        "## Concentration Summary",
        "",
    ]
    if summary.empty:
        lines.append("- No Phase 5F fold results were available.")
    else:
        lines.extend([
            "| Candidate | Label | Total Net | 4-Tick Slip | Positive Folds | Best Fold | Best Fold % | Max Day % | Max Trade % | Notes |",
            "| --- | --- | ---: | ---: | ---: | --- | ---: | ---: | ---: | --- |",
        ])
        for _, row in summary.iterrows():
            lines.append(
                f"| `{row['candidate_id']}` | {row['concentration_label']} | ${row['total_net_pnl']:.2f} | ${row['total_slippage_4_ticks_net_pnl']:.2f} | {int(row['positive_folds'])}/{int(row['folds'])} | {int(row['best_fold'])} ${row['best_fold_pnl']:.2f} | {row['best_fold_concentration'] * 100:.1f}% | {row['max_test_best_day_concentration'] * 100:.1f}% | {row['max_test_best_trade_concentration'] * 100:.1f}% | {row['concentration_notes']} |"
            )
        lines.extend(["", "## Readout", "", f"- Label counts: `{summary['concentration_label'].value_counts().to_dict()}`"])
    lines.extend([
        "",
        "## Interpretation",
        "",
        "- `distributed` means no fold/day/trade concentration threshold was exceeded in the current fold-level screen.",
        "- `concentrated` means the candidate remains interesting but should not be promoted without further filtering or broader validation.",
        "- A concentrated result can still be useful for research; it is not a paper-test approval.",
        "",
        "## Repro Command",
        "",
        "```bash",
        "./.venv/Scripts/python.exe scripts/run_phase5g_concentration_diagnostics.py",
        "```",
        "",
    ])
    return "\n".join(lines)


if __name__ == "__main__":
    main()
