from __future__ import annotations

import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
SRC_ROOT = PROJECT_ROOT / "src"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from short_term_edge.phase5n import Phase5NConfig, run_phase5n_prefilter, write_phase5n_specs  # noqa: E402


def main() -> None:
    output_dir = PROJECT_ROOT / "outputs"
    report_dir = PROJECT_ROOT / "reports"
    output_dir.mkdir(parents=True, exist_ok=True)
    report_dir.mkdir(parents=True, exist_ok=True)

    results_path = output_dir / "phase5n_prefilter_results.csv"
    specs_path = output_dir / "phase5n_candidate_specs.json"
    report_path = report_dir / "phase5n_full_history_prefilter_report.md"

    config = Phase5NConfig(symbol="MNQ", max_specs=40, min_specs=40, batch_size=1)
    result = run_phase5n_prefilter(PROJECT_ROOT, config, checkpoint_path=results_path)

    result.search_results.to_csv(results_path, index=False)
    write_phase5n_specs(result.specs, specs_path)
    report_path.write_text(_report(config, result, results_path, specs_path, report_path), encoding="utf-8")

    print("Phase 5N full-history deterministic family prefilter complete.")
    print(f"Search results: {results_path}")
    print(f"Candidate specs: {specs_path}")
    print(f"Report: {report_path}")
    print(f"Evaluated specs: {len(result.specs)}")
    print(f"Complete MNQ sessions: {len(result.complete_sessions)}")
    if not result.search_results.empty:
        top = result.search_results.iloc[0]
        survivors = int(result.search_results["phase5n_label"].eq("prefilter_survivor").sum())
        print(
            f"Top: {top['candidate_id']} score={top['phase5n_score']} label={top['phase5n_label']} "
            f"net={top['net_pnl']:.2f} 4tick={top['slippage_4_ticks_net_pnl']:.2f} survivors={survivors}"
        )


def _report(config: Phase5NConfig, result, results_path: Path, specs_path: Path, report_path: Path) -> str:
    labels = result.search_results["phase5n_label"].value_counts().to_dict() if not result.search_results.empty else {}
    lines = [
        "# Phase 5N Full-History Deterministic Family Prefilter Report",
        "",
        "Generated by: `./.venv/Scripts/python.exe scripts/run_phase5n_full_history_prefilter.py`",
        "",
        "## Scope And Guardrails",
        "",
        "- Research/simulation only. No live trading, broker adapters, API-key storage, webhooks, order routing, or automated execution were added.",
        "- Phase 5N is an MNQ-only deterministic full-history family prefilter over local CSV data under `data/raw`.",
        "- Strategy specs are deterministic and serializable; no opaque ML or LLM trade decisions were added.",
        "- Ranking strictly penalizes 4-tick slippage failure, concentration, active-day coverage, trade count, and drawdown.",
        "",
        "## Configuration",
        "",
        f"- Symbol: `{config.symbol}`",
        f"- Candidate cap: `{config.max_specs}` specs; selected `{len(result.specs)}` specs",
        f"- Checkpoint batch size: `{config.batch_size}` specs; existing candidate IDs are skipped on resume",
        f"- Timeframes: `{config.timeframes}`",
        f"- Opening-range minutes: `{config.opening_range_minutes}`",
        f"- Complete MNQ sessions: `{len(result.complete_sessions)}`",
        f"- Label counts: `{labels}`",
        "",
        "## Outputs",
        "",
        f"- Search results: `{results_path}`",
        f"- Candidate specs: `{specs_path}`",
        f"- Report: `{report_path}`",
        "",
        "## Top Ranked Results",
        "",
    ]
    if result.search_results.empty:
        lines.append("No results were produced.")
    else:
        lines.extend(
            [
                "| Rank | Candidate | Family | TF | Label | Score | Net PnL | 4-Tick Slip | Trades | Active % | Max DD | Day Conc. | Trade Conc. | Notes |",
                "| ---: | --- | --- | ---: | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- |",
            ]
        )
        for _, row in result.search_results.head(15).iterrows():
            lines.append(
                f"| {int(row['phase5n_rank'])} | `{row['candidate_id']}` | {row['family']} | {int(row['timeframe'])} | {row['phase5n_label']} | {row['phase5n_score']:.2f} | ${row['net_pnl']:.2f} | ${row['slippage_4_ticks_net_pnl']:.2f} | {int(row['trades'])} | {row['active_session_pct'] * 100:.1f}% | ${row['max_drawdown']:.2f} | {row['best_day_concentration'] * 100:.1f}% | {row['best_trade_concentration'] * 100:.1f}% | {row['phase5n_notes']} |"
            )
    lines.extend(
        [
            "",
            "## Interpretation",
            "",
            "- `prefilter_survivor` means a candidate survived cheap full-history gates and should be deep walk-forward validated in Phase 5O before any paper-trading consideration.",
            "- `watchlist_needs_walk_forward` means the candidate passed core stress/activity/concentration checks but had a weak validation or holdout split.",
            "- `rejected` means it failed one or more full-history prefilter gates.",
            "",
            "## Repro Command",
            "",
            "```bash",
            "./.venv/Scripts/python.exe scripts/run_phase5n_full_history_prefilter.py",
            "```",
            "",
        ]
    )
    return "\n".join(lines)


if __name__ == "__main__":
    main()
