from __future__ import annotations

import os
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
SRC_ROOT = PROJECT_ROOT / "src"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from short_term_edge.phase7a import Phase7AConfig, run_phase7a_reproduction, write_phase7a_specs  # noqa: E402


def main() -> None:
    output_dir = PROJECT_ROOT / "outputs"
    report_dir = PROJECT_ROOT / "reports"
    output_dir.mkdir(parents=True, exist_ok=True)
    report_dir.mkdir(parents=True, exist_ok=True)

    max_new = int(os.environ.get("PHASE7A_MAX_NEW_SPECS", "6"))
    config = Phase7AConfig(symbol="MGC", max_specs=6, min_specs=6, batch_size=1, max_new_specs_per_run=max_new)
    results_path = output_dir / "phase7a_mgc_reproduction_results.csv"
    specs_path = output_dir / "phase7a_candidate_specs.json"
    report_path = report_dir / "phase7a_mgc_reproduction_report.md"

    result = run_phase7a_reproduction(PROJECT_ROOT, config, checkpoint_path=results_path)
    result.search_results.to_csv(results_path, index=False)
    write_phase7a_specs(result.specs, specs_path)
    report_path.write_text(_render_report(config, result, results_path, specs_path, report_path), encoding="utf-8")

    print("Phase 7A MGC reproduction prefilter complete.")
    print(f"Search results: {results_path}")
    print(f"Candidate specs: {specs_path}")
    print(f"Report: {report_path}")
    print(f"Rows scored: {len(result.search_results)} / {len(result.specs)} selected specs")
    if not result.search_results.empty:
        top = result.search_results.iloc[0]
        print(
            f"Top candidate: {top['candidate_id']} family={top['family']} "
            f"score={top['phase7a_score']} label={top['phase7a_label']} net={top['net_pnl']:.2f}"
        )


def _render_report(config: Phase7AConfig, result, results_path: Path, specs_path: Path, report_path: Path) -> str:
    label_counts = result.search_results["phase7a_label"].value_counts().to_dict() if not result.search_results.empty else {}
    family_counts = result.search_results.groupby("family")["candidate_id"].count().to_dict() if not result.search_results.empty else {}
    lines = [
        "# Phase 7A MGC Old-Project Reproduction Prefilter Report",
        "",
        "Generated by: `./.venv/Scripts/python.exe scripts/run_phase7a_mgc_reproduction.py`",
        "",
        "## Scope And Guardrails",
        "",
        "- Research/simulation only. No live trading, broker adapters, API-key storage, webhooks, order routing, or automated execution were added.",
        "- Phase 7A is MGC-only and uses local CSV-derived data under `data/raw`.",
        "- This ports ideas from the older local project as deterministic current-project strategy specs, not as executable broker/NinjaTrader automation.",
        "- Candidate specs are deterministic and serializable; no LLM-driven trade entries/exits/sizing were added.",
        "",
        "## Imported Ideas From Older Project",
        "",
        "- `vwap_pullback_continuation`: short-only VWAP pullback/rejection continuation with 2-3 tick pullback, 6/8 tick stop buffers, 1R-style target.",
        "- `opening_drive_continuation`: 5/10 minute opening-drive continuation with 4/8 tick minimum drive, 1 tick breakout/stop buffer, 2R target.",
        "- The old project found these ideas most useful on MGC and inside combo/risk-gated workflows; Phase 7A tests them as standalone prefilter components first.",
        "",
        "## Configuration",
        "",
        f"- Symbol: `{config.symbol}`",
        f"- Candidate cap: `{config.max_specs}` specs; selected `{len(result.specs)}` specs",
        f"- Timeframes: `{config.timeframes}`",
        f"- Max new specs this invocation: `{config.max_new_specs_per_run}` (set `PHASE7A_MAX_NEW_SPECS` to adjust bounded batches)",
        f"- Complete MGC sessions: `{len(result.complete_sessions)}`" if result.complete_sessions else "- Complete MGC sessions: not reloaded during checkpoint-only refresh",
        f"- Label counts: `{label_counts}`",
        f"- Family rows scored: `{family_counts}`",
        "",
        "## Outputs",
        "",
        f"- Search results: `{results_path}`",
        f"- Candidate specs: `{specs_path}`",
        f"- Report: `{report_path}`",
        "",
        "## Top Ranked Results",
        "",
        "| Rank | Candidate | Family | TF | Label | Score | Net PnL | 4-Tick Slip | Trades | Active % | Max DD | Day Conc. | Trade Conc. | Notes |",
        "| ---: | --- | --- | ---: | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- |",
    ]
    if not result.search_results.empty:
        for _, row in result.search_results.head(15).iterrows():
            lines.append(
                f"| {int(row['phase7a_rank'])} | `{row['candidate_id']}` | {row['family']} | {int(row['timeframe'])} | {row['phase7a_label']} | {row['phase7a_score']:.2f} | ${row['net_pnl']:.2f} | ${row['slippage_4_ticks_net_pnl']:.2f} | {int(row['trades'])} | {row['active_session_pct'] * 100:.1f}% | ${row['max_drawdown']:.2f} | {row['best_day_concentration'] * 100:.1f}% | {row['best_trade_concentration'] * 100:.1f}% | {row['phase7a_notes']} |"
            )
    lines.extend(
        [
            "",
            "## Interpretation",
            "",
            "- `mgc_reproduction_prefilter_survivor` means a ported MGC component survived cheap full-history gates and needs walk-forward validation before any paper-test consideration.",
            "- `mgc_reproduction_watchlist` means core full-history gates passed but validation/holdout split behavior was weak.",
            "- `rejected` means it failed one or more prefilter gates.",
            "",
            "## Repro Command",
            "",
            "```bash",
            "PHASE7A_MAX_NEW_SPECS=6 ./.venv/Scripts/python.exe scripts/run_phase7a_mgc_reproduction.py",
            "```",
            "",
        ]
    )
    return "\n".join(lines)


if __name__ == "__main__":
    main()
