from __future__ import annotations

import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
SRC_ROOT = PROJECT_ROOT / "src"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from short_term_edge.phase5m import Phase5MConfig, run_phase5m_validation, write_phase5m_spec  # noqa: E402
from short_term_edge.walk_forward import WalkForwardConfig  # noqa: E402


def main() -> None:
    output_dir = PROJECT_ROOT / "outputs"
    report_dir = PROJECT_ROOT / "reports"
    output_dir.mkdir(parents=True, exist_ok=True)
    report_dir.mkdir(parents=True, exist_ok=True)

    config = Phase5MConfig(
        symbol="MNQ",
        walk_forward=WalkForwardConfig(train_sessions=120, validation_sessions=30, test_sessions=30, step_sessions=360, min_folds=2, max_candidates=1),
    )
    result = run_phase5m_validation(PROJECT_ROOT, config)

    fold_path = output_dir / "phase5m_deep_vwap_fold_results.csv"
    results_path = output_dir / "phase5m_deep_vwap_results.csv"
    spec_path = output_dir / "phase5m_candidate_spec.json"
    report_path = report_dir / "phase5m_deep_vwap_validation_report.md"

    result.fold_results.to_csv(fold_path, index=False)
    result.search_results.to_csv(results_path, index=False)
    write_phase5m_spec(result.spec, spec_path)
    report_path.write_text(_report(config, result, fold_path, results_path, spec_path, report_path), encoding="utf-8")

    print("Phase 5M deep VWAP validation complete.")
    print(f"Fold results: {fold_path}")
    print(f"Search results: {results_path}")
    print(f"Candidate spec: {spec_path}")
    print(f"Report: {report_path}")
    if not result.search_results.empty:
        top = result.search_results.iloc[0]
        print(f"Candidate: {top['candidate_id']} folds={int(top['folds'])} score={top['phase5m_score']} label={top['phase5m_label']} test_net={top['test_net_pnl']:.2f}")


def _report(config: Phase5MConfig, result, fold_path: Path, results_path: Path, spec_path: Path, report_path: Path) -> str:
    lines = [
        "# Phase 5M Deep VWAP Validation Report",
        "",
        "Generated by: `./.venv/Scripts/python.exe scripts/run_phase5m_deep_vwap_validation.py`",
        "",
        "## Scope And Guardrails",
        "",
        "- Research/simulation only. No live trading, broker adapters, API-key storage, webhooks, order routing, or automated execution were added.",
        "- Phase 5M deep-validates the top Phase 5K VWAP candidate over multiple chronological folds.",
        "- The strategy remains deterministic and serializable; no opaque ML signal generation was added.",
        "- Source data is local only under `data/raw`; no data was downloaded.",
        "",
        "## Validation Configuration",
        "",
        f"- Symbol: `{config.symbol}`",
        f"- Candidate: `{result.spec.canonical_id()}`",
        f"- Walk-forward train/validation/test: `{config.walk_forward.train_sessions}/{config.walk_forward.validation_sessions}/{config.walk_forward.test_sessions}` sessions",
        f"- Step sessions: `{config.walk_forward.step_sessions}`",
        f"- Generated folds: `{len(result.folds)}`",
        "",
        "## Outputs",
        "",
        f"- Fold results: `{fold_path}`",
        f"- Search results: `{results_path}`",
        f"- Candidate spec: `{spec_path}`",
        f"- Report: `{report_path}`",
        "",
        "## Result",
        "",
    ]
    if result.search_results.empty:
        lines.append("No result was produced.")
    else:
        row = result.search_results.iloc[0]
        lines.extend([
            "| Candidate | Label | Score | Test Net | 4-Tick Slip | Positive Folds | Active % | Day Conc. | Trade Conc. | Notes |",
            "| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- |",
            f"| `{row['candidate_id']}` | {row['phase5m_label']} | {row['phase5m_score']:.2f} | ${row['test_net_pnl']:.2f} | ${row['test_slippage_4_ticks_net_pnl']:.2f} | {int(row['test_positive_folds'])}/{int(row['folds'])} | {row['test_active_session_pct'] * 100:.1f}% | {row['test_best_day_concentration'] * 100:.1f}% | {row['test_best_trade_concentration'] * 100:.1f}% | {row['phase5m_notes']} |",
            "",
            "## Fold Results",
            "",
            "| Fold | Segment | Net PnL | 4-Tick Slip | Trades | Active Sessions | Max DD |",
            "| ---: | --- | ---: | ---: | ---: | ---: | ---: |",
        ])
        for _, fold_row in result.fold_results.iterrows():
            lines.append(
                f"| {int(fold_row['fold'])} | {fold_row['segment']} | ${fold_row['net_pnl']:.2f} | ${fold_row['slippage_4_ticks_net_pnl']:.2f} | {int(fold_row['trades'])} | {int(fold_row['active_sessions'])} | ${fold_row['max_drawdown']:.2f} |"
            )
    lines.extend([
        "",
        "## Interpretation",
        "",
        "- `deep_vwap_candidate` means the candidate survived multi-fold validation and current concentration thresholds.",
        "- `watchlist_concentrated` means profitable but still too concentrated for paper-test promotion.",
        "- `rejected` means the candidate failed fold or slippage survival.",
        "",
        "## Repro Command",
        "",
        "```bash",
        "./.venv/Scripts/python.exe scripts/run_phase5m_deep_vwap_validation.py",
        "```",
        "",
    ])
    return "\n".join(lines)


if __name__ == "__main__":
    main()
