from __future__ import annotations

import sys
import os
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
SRC_ROOT = PROJECT_ROOT / "src"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from short_term_edge.phase6a import Phase6AConfig, run_phase6a_expansion, write_phase6a_specs  # noqa: E402


def main() -> None:
    output_dir = PROJECT_ROOT / "outputs"
    report_dir = PROJECT_ROOT / "reports"
    output_dir.mkdir(parents=True, exist_ok=True)
    report_dir.mkdir(parents=True, exist_ok=True)

    results_path = output_dir / "phase6a_expansion_results.csv"
    specs_path = output_dir / "phase6a_candidate_specs.json"
    report_path = report_dir / "phase6a_search_dimension_expansion_report.md"

    max_new_specs = int(os.environ.get("PHASE6A_MAX_NEW_SPECS", "3"))
    config = Phase6AConfig(symbol="MNQ", max_specs=48, min_specs=40, batch_size=1, max_new_specs_per_run=max_new_specs)
    result = run_phase6a_expansion(PROJECT_ROOT, config, checkpoint_path=results_path)

    result.search_results.to_csv(results_path, index=False)
    write_phase6a_specs(result.specs, specs_path)
    report_path.write_text(_report(config, result, results_path, specs_path, report_path), encoding="utf-8")

    print("Phase 6A deterministic search-dimension expansion complete.")
    print(f"Search results: {results_path}")
    print(f"Candidate specs: {specs_path}")
    print(f"Report: {report_path}")
    completed = int(result.search_results["candidate_id"].nunique()) if not result.search_results.empty else 0
    print(f"Candidate specs: {len(result.specs)} selected; {completed} scored in checkpoint")
    if config.max_new_specs_per_run == 0 and not result.complete_sessions:
        print("Complete MNQ sessions: not recomputed during checkpoint-only refresh")
    else:
        print(f"Complete MNQ sessions: {len(result.complete_sessions)}")
    if not result.search_results.empty:
        top = result.search_results.iloc[0]
        survivors = int(result.search_results["phase6a_label"].eq("prefilter_survivor").sum())
        watchlist = int(result.search_results["phase6a_label"].eq("watchlist_needs_walk_forward").sum())
        print(
            f"Top: {top['candidate_id']} score={top['phase6a_score']} label={top['phase6a_label']} "
            f"net={top['net_pnl']:.2f} 4tick={top['slippage_4_ticks_net_pnl']:.2f} "
            f"survivors={survivors} watchlist={watchlist}"
        )


def _report(config: Phase6AConfig, result, results_path: Path, specs_path: Path, report_path: Path) -> str:
    labels = result.search_results["phase6a_label"].value_counts().to_dict() if not result.search_results.empty else {}
    lines = [
        "# Phase 6A Deterministic Search-Dimension Expansion Report",
        "",
        "Generated by: `./.venv/Scripts/python.exe scripts/run_phase6a_search_dimension_expansion.py`",
        "",
        "## Scope And Guardrails",
        "",
        "- Research/simulation only. No live trading, broker adapters, API-key storage, webhooks, order routing, or automated execution were added.",
        "- Phase 6A runs MNQ-only against local CSV data under `data/raw` after Phase 5N produced no prefilter survivors.",
        "- The expansion is deterministic and serializable; it adds no opaque ML or LLM trade decisions.",
        "- Ranking reuses strict Phase 5N-style penalties for 4-tick slippage, concentration, active-day coverage, trade count, split robustness, and drawdown.",
        "",
        "## Configuration",
        "",
        f"- Symbol: `{config.symbol}`",
        f"- Candidate cap: `{config.max_specs}` specs; selected `{len(result.specs)}` specs",
        f"- Checkpoint batch size: `{config.batch_size}` specs; existing candidate IDs are skipped on resume",
        f"- Max new specs this invocation: `{config.max_new_specs_per_run}` (set `PHASE6A_MAX_NEW_SPECS` to adjust bounded batches)",
        f"- Timeframes: `{config.timeframes}`",
        f"- Opening-range minutes: `{config.opening_range_minutes}`",
        "- New dimensions include 2-minute signal bars, 5/90-minute opening ranges, 20/30 and wider 40/80 and 60/120 fixed-tick exits.",
        _complete_sessions_line(config, result),
        f"- Label counts: `{labels}`",
        "",
        "## Outputs",
        "",
        f"- Search results: `{results_path}`",
        f"- Candidate specs: `{specs_path}`",
        f"- Report: `{report_path}`",
        "",
        "## Top Ranked Results",
        "",
    ]
    if result.search_results.empty:
        lines.append("No results were produced.")
    else:
        lines.extend(
            [
                "| Rank | Candidate | Family | TF | Label | Score | Net PnL | 4-Tick Slip | Trades | Active % | Max DD | Day Conc. | Trade Conc. | Notes |",
                "| ---: | --- | --- | ---: | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- |",
            ]
        )
        for _, row in result.search_results.head(15).iterrows():
            lines.append(
                f"| {int(row['phase6a_rank'])} | `{row['candidate_id']}` | {row['family']} | {int(row['timeframe'])} | {row['phase6a_label']} | {row['phase6a_score']:.2f} | ${row['net_pnl']:.2f} | ${row['slippage_4_ticks_net_pnl']:.2f} | {int(row['trades'])} | {row['active_session_pct'] * 100:.1f}% | ${row['max_drawdown']:.2f} | {row['best_day_concentration'] * 100:.1f}% | {row['best_trade_concentration'] * 100:.1f}% | {row['phase6a_notes']} |"
            )
    lines.extend(
        [
            "",
            "## Interpretation",
            "",
            "- `prefilter_survivor` means a deterministic expanded candidate survived cheap full-history gates and should be deep walk-forward validated before paper-trading consideration.",
            "- `watchlist_needs_walk_forward` means core stress/activity/concentration gates passed but a validation or holdout split was weak.",
            "- `rejected` means the candidate failed one or more full-history gates.",
            "",
            "## Repro Command",
            "",
            "```bash",
            "./.venv/Scripts/python.exe scripts/run_phase6a_search_dimension_expansion.py",
            "```",
            "",
        ]
    )
    return "\n".join(lines)


def _complete_sessions_line(config: Phase6AConfig, result) -> str:
    if config.max_new_specs_per_run == 0 and not result.complete_sessions:
        return "- Complete MNQ sessions: not recomputed during checkpoint-only refresh"
    return f"- Complete MNQ sessions: `{len(result.complete_sessions)}`"


if __name__ == "__main__":
    main()
