from __future__ import annotations

import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
SRC_ROOT = PROJECT_ROOT / "src"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from short_term_edge.walk_forward import WalkForwardConfig, run_walk_forward_validation  # noqa: E402


def main() -> None:
    output_dir = PROJECT_ROOT / "outputs"
    report_dir = PROJECT_ROOT / "reports"
    output_dir.mkdir(parents=True, exist_ok=True)
    report_dir.mkdir(parents=True, exist_ok=True)

    config = WalkForwardConfig(
        train_sessions=240,
        validation_sessions=60,
        test_sessions=60,
        step_sessions=240,
        min_folds=2,
        max_candidates=3,
    )
    result = run_walk_forward_validation(PROJECT_ROOT, config)

    fold_results_path = output_dir / "phase5d_walk_forward_results.csv"
    summary_path = output_dir / "phase5d_candidate_summary.csv"
    report_path = report_dir / "phase5d_walk_forward_report.md"
    result.fold_results.to_csv(fold_results_path, index=False)
    result.candidate_summary.to_csv(summary_path, index=False)
    report_path.write_text(_report(result, config, fold_results_path, summary_path), encoding="utf-8")

    print("Phase 5D walk-forward validation complete.")
    print(f"Fold results: {fold_results_path}")
    print(f"Candidate summary: {summary_path}")
    print(f"Report: {report_path}")
    print(f"Folds: {len(result.folds)}")
    print(f"Candidates: {len(result.specs)}")
    if not result.candidate_summary.empty:
        top = result.candidate_summary.iloc[0]
        print(f"Top candidate: {top['candidate_id']} score={top['phase5d_score']} label={top['phase5d_label']} test_net={top['test_net_pnl']:.2f}")


def _report(result, config: WalkForwardConfig, fold_results_path: Path, summary_path: Path) -> str:
    summary = result.candidate_summary
    lines = [
        "# Phase 5D Walk-Forward Validation Report",
        "",
        "Generated by: `./.venv/Scripts/python.exe scripts/run_phase5d_walk_forward.py`",
        "",
        "## Scope And Guardrails",
        "",
        "- Research/simulation only. No live trading, broker adapters, API-key storage, webhooks, order routing, or automated execution were added.",
        "- Phase 5D validates existing Phase 5C deterministic strategy specs; it does not create live signals.",
        "- Source data is local only under `data/raw`; no data was downloaded.",
        "- Folds are chronological train/validation/test windows with no shuffling.",
        "",
        "## Walk-Forward Configuration",
        "",
        f"- Train sessions per fold: `{config.train_sessions}`",
        f"- Validation sessions per fold: `{config.validation_sessions}`",
        f"- Test sessions per fold: `{config.test_sessions}`",
        f"- Step sessions: `{config.step_sessions}`",
        f"- Folds generated: `{len(result.folds)}`",
        f"- Candidates evaluated: `{len(result.specs)}`",
        "",
        "## Outputs",
        "",
        f"- Fold-level results: `{fold_results_path}`",
        f"- Candidate summary: `{summary_path}`",
        f"- Report: `{PROJECT_ROOT / 'reports' / 'phase5d_walk_forward_report.md'}`",
        "",
        "## Fold Windows",
        "",
        "| Fold | Train | Validation | Test |",
        "| ---: | --- | --- | --- |",
    ]
    for fold in result.folds:
        lines.append(
            f"| {fold.fold} | `{fold.train_sessions[0]}` to `{fold.train_sessions[-1]}` | `{fold.validation_sessions[0]}` to `{fold.validation_sessions[-1]}` | `{fold.test_sessions[0]}` to `{fold.test_sessions[-1]}` |"
        )

    lines.extend(["", "## Candidate Promotion Summary", ""])
    if summary.empty:
        lines.append("- No candidates were evaluated.")
    else:
        lines.extend(
            [
                "| Rank | Candidate | Symbol | TF | Label | Score | Test Net | Test 4-Tick Slip | Positive Test Folds | Trades | Active % | Notes |",
                "| ---: | --- | --- | ---: | --- | ---: | ---: | ---: | ---: | ---: | ---: | --- |",
            ]
        )
        for rank, (_, row) in enumerate(summary.iterrows(), start=1):
            lines.append(
                f"| {rank} | `{row['candidate_id']}` | {row['instrument']} | {int(row['timeframe'])}m | {row['phase5d_label']} | {row['phase5d_score']:.2f} | ${row['test_net_pnl']:.2f} | ${row['test_slippage_4_ticks_net_pnl']:.2f} | {int(row['test_positive_folds'])}/{int(row['folds'])} | {int(row['test_trades'])} | {row['test_active_session_pct'] * 100:.1f}% | {row['phase5d_notes']} |"
            )
        lines.extend(["", "## Readout", "", f"- Label counts: `{summary['phase5d_label'].value_counts().to_dict()}`"])

    lines.extend(
        [
            "",
            "## Interpretation",
            "",
            "- `paper_test_candidate` means a candidate survived the Phase 5D walk-forward gates; it is still for manual paper testing only.",
            "- `robust_research_candidate` means the candidate remains interesting but needs more validation or less fragility.",
            "- `watchlist` and `rejected` candidates should not be promoted to paper testing without further research.",
            "",
            "## Repro Command",
            "",
            "```bash",
            "./.venv/Scripts/python.exe scripts/run_phase5d_walk_forward.py",
            "```",
            "",
        ]
    )
    return "\n".join(lines)


if __name__ == "__main__":
    main()
