from __future__ import annotations

import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
SRC_ROOT = PROJECT_ROOT / "src"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from short_term_edge.phase5h import Phase5HConfig, run_phase5h_search, write_phase5h_specs  # noqa: E402
from short_term_edge.walk_forward import WalkForwardConfig  # noqa: E402


def main() -> None:
    output_dir = PROJECT_ROOT / "outputs"
    report_dir = PROJECT_ROOT / "reports"
    output_dir.mkdir(parents=True, exist_ok=True)
    report_dir.mkdir(parents=True, exist_ok=True)

    config = Phase5HConfig(
        symbols=("MNQ",),
        max_specs=1,
        walk_forward=WalkForwardConfig(train_sessions=120, validation_sessions=30, test_sessions=30, step_sessions=360, min_folds=2, max_candidates=1),
    )
    result = run_phase5h_search(PROJECT_ROOT, config)

    fold_path = output_dir / "phase5h_regime_filtered_fold_results.csv"
    results_path = output_dir / "phase5h_regime_filtered_results.csv"
    specs_path = output_dir / "phase5h_candidate_specs.json"
    report_path = report_dir / "phase5h_regime_filtered_search_report.md"

    result.fold_results.to_csv(fold_path, index=False)
    result.search_results.to_csv(results_path, index=False)
    write_phase5h_specs(result.specs, specs_path)
    report_path.write_text(_report(config, result, fold_path, results_path, specs_path, report_path), encoding="utf-8")

    print("Phase 5H regime-filtered deterministic search complete.")
    print(f"Fold results: {fold_path}")
    print(f"Search results: {results_path}")
    print(f"Candidate specs: {specs_path}")
    print(f"Report: {report_path}")
    print(f"Candidates evaluated: {len(result.search_results)}")
    if not result.search_results.empty:
        top = result.search_results.iloc[0]
        print(f"Top candidate: {top['candidate_id']} filter={top['regime_filter']} score={top['phase5h_score']} label={top['phase5h_label']} test_net={top['test_net_pnl']:.2f}")


def _report(config: Phase5HConfig, result, fold_path: Path, results_path: Path, specs_path: Path, report_path: Path) -> str:
    lines = [
        "# Phase 5H Regime-Filtered Search Report",
        "",
        "Generated by: `./.venv/Scripts/python.exe scripts/run_phase5h_regime_filtered_search.py`",
        "",
        "## Scope And Guardrails",
        "",
        "- Research/simulation only. No live trading, broker adapters, API-key storage, webhooks, order routing, or automated execution were added.",
        "- Phase 5H evaluates deterministic regime filters on existing walk-forward candidate families.",
        "- Filters use prior-session/opening-regime context from Phase 5B features; future `label_*` columns are not used.",
        "- Source data is local only under `data/raw`; no data was downloaded.",
        "",
        "## Search Configuration",
        "",
        f"- Symbols: `{', '.join(config.symbols)}`",
        f"- Candidate specs: `{config.max_specs}`",
        "- Regime filters: `all`, `prior_range_bucket=mid`, `prior_range_bucket=high`, `gap_abs_bucket=low`, `or_width_bucket=mid`",
        f"- Walk-forward train/validation/test: `{config.walk_forward.train_sessions}/{config.walk_forward.validation_sessions}/{config.walk_forward.test_sessions}` sessions",
        f"- Step sessions: `{config.walk_forward.step_sessions}`",
        "",
        "## Outputs",
        "",
        f"- Fold results: `{fold_path}`",
        f"- Search results: `{results_path}`",
        f"- Candidate specs: `{specs_path}`",
        f"- Report: `{report_path}`",
        "",
        "## Top Results",
        "",
    ]
    if result.search_results.empty:
        lines.append("No results were produced.")
    else:
        lines.extend([
            "| Rank | Candidate | Filter | Label | Score | Test Net | 4-Tick Slip | Positive Folds | Active % | Day Conc. | Trade Conc. | Notes |",
            "| ---: | --- | --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- |",
        ])
        for _, row in result.search_results.head(10).iterrows():
            lines.append(
                f"| {int(row['phase5h_rank'])} | `{row['candidate_id']}` | `{row['regime_filter']}` | {row['phase5h_label']} | {row['phase5h_score']:.2f} | ${row['test_net_pnl']:.2f} | ${row['test_slippage_4_ticks_net_pnl']:.2f} | {int(row['test_positive_folds'])}/{int(row['folds'])} | {row['test_active_session_pct'] * 100:.1f}% | {row['test_best_day_concentration'] * 100:.1f}% | {row['test_best_trade_concentration'] * 100:.1f}% | {row['phase5h_notes']} |"
            )
        lines.extend(["", "## Readout", "", f"- Label counts: `{result.search_results['phase5h_label'].value_counts().to_dict()}`"])
    lines.extend([
        "",
        "## Interpretation",
        "",
        "- `regime_filtered_candidate` means the filter passed slippage/positive-fold checks and reduced concentration below current thresholds.",
        "- `watchlist_concentrated` means the result remains profitable but still too concentrated for paper-test promotion.",
        "- `rejected` means the filter failed fold or slippage survival.",
        "",
        "## Repro Command",
        "",
        "```bash",
        "./.venv/Scripts/python.exe scripts/run_phase5h_regime_filtered_search.py",
        "```",
        "",
    ])
    return "\n".join(lines)


if __name__ == "__main__":
    main()
