from __future__ import annotations

from collections import Counter
from typing import Iterable

import pandas as pd


def summarize_note_counts(results: pd.DataFrame, note_columns: Iterable[str]) -> pd.DataFrame:
    counter: Counter[str] = Counter()
    for column in note_columns:
        if column not in results.columns:
            continue
        for raw_notes in results[column].fillna(""):
            for note in str(raw_notes).split(";"):
                cleaned = note.strip()
                if cleaned:
                    counter[cleaned] += 1
    rows = [{"failure_mode": mode, "count": count} for mode, count in counter.items()]
    if not rows:
        return pd.DataFrame(columns=["failure_mode", "count"]).set_index("failure_mode")
    return pd.DataFrame(rows).sort_values(["count", "failure_mode"], ascending=[False, True]).set_index("failure_mode")


def summarize_failure_categories(failure_modes: pd.DataFrame) -> pd.DataFrame:
    category_counts: Counter[str] = Counter()
    for failure_mode, row in failure_modes.iterrows():
        category_counts[_failure_category(str(failure_mode))] += int(row["count"])
    rows = [{"failure_category": category, "count": count} for category, count in category_counts.items()]
    if not rows:
        return pd.DataFrame(columns=["failure_category", "count"]).set_index("failure_category")
    return pd.DataFrame(rows).sort_values(["count", "failure_category"], ascending=[False, True]).set_index("failure_category")


def render_phase6_failure_synthesis(phase6a_results: pd.DataFrame, phase6b_results: pd.DataFrame) -> str:
    phase6a_count = _candidate_count(phase6a_results)
    phase6b_count = _candidate_count(phase6b_results)
    phase6a_labels = _label_counts(phase6a_results, "phase6a_label")
    phase6b_labels = _label_counts(phase6b_results, "phase6b_label")
    phase6a_failure_modes = summarize_note_counts(phase6a_results, ("phase6a_notes",))
    phase6b_failure_modes = summarize_note_counts(phase6b_results, ("phase6b_notes",))
    combined_failure_modes = summarize_note_counts(
        pd.concat([phase6a_results, phase6b_results], ignore_index=True, sort=False),
        ("phase6a_notes", "phase6b_notes"),
    )
    failure_categories = summarize_failure_categories(combined_failure_modes)
    phase6b_survivors = _survivor_count(phase6b_results)

    lines = [
        "# Phase 6 Failure Synthesis Report",
        "",
        "Generated by: `./.venv/Scripts/python.exe scripts/run_phase6_failure_synthesis.py`",
        "",
        "## Scope And Guardrails",
        "",
        "- Research/simulation only. No live trading, broker adapters, API-key storage, webhooks, order routing, or automated execution were added.",
        "- Synthesis uses only local Phase 6 CSV outputs derived from local CSV files under `data/raw`.",
        "- MNQ lessons are captured before considering any instrument expansion.",
        "- No candidate in this report is approved for live trading or paper trading without separate deep validation.",
        "",
        "## Completed Work",
        "",
        f"- Phase 6A: {phase6a_count} scored Phase 6A candidates; label counts: `{phase6a_labels}`.",
        f"- Phase 6B: {phase6b_count} scored Phase 6B candidates; label counts: `{phase6b_labels}`.",
        f"- Phase 6B survivor/watchlist count: `{phase6b_survivors}`.",
        "",
        "## Best Candidates By Phase",
        "",
    ]
    lines.extend(_candidate_table("Phase 6A", phase6a_results, "phase6a_rank", "phase6a_label", "phase6a_score", "phase6a_notes"))
    lines.append("")
    lines.extend(_candidate_table("Phase 6B", phase6b_results, "phase6b_rank", "phase6b_label", "phase6b_score", "phase6b_notes"))
    lines.extend(
        [
            "",
            "## Failure Modes",
            "",
            "### Phase 6A",
            "",
        ]
    )
    lines.extend(_failure_mode_table(phase6a_failure_modes))
    lines.extend(["", "### Phase 6B", ""])
    lines.extend(_failure_mode_table(phase6b_failure_modes))
    lines.extend(["", "### Combined Phase 6", ""])
    lines.extend(_failure_mode_table(combined_failure_modes))
    lines.extend(["", "### Failure Category Totals", ""])
    lines.extend(_failure_category_table(failure_categories))
    lines.extend(
        [
            "",
            "## Interpretation",
            "",
            "- Phase 6A failed primarily on concentration, drawdown, and cost/slippage resilience rather than lack of raw opportunity.",
            "- Phase 6B reduced ambiguity and improved the top raw economics, but the best candidate still failed concentration/drawdown gates.",
            "- No Phase 6B prefilter survivors or watchlist candidates were found, so Phase 6C deep validation is not justified yet.",
            "- The observed failures are dominated by concentration and drawdown, with slippage/cost stress still killing most non-top candidates.",
            "",
            "## Recommendation",
            "",
            "- Stop broad MNQ expansion for now; do not paper-trade these Phase 6 candidates.",
            "- Next research axis should test lower-frequency session-selection strategies that explicitly choose when not to trade.",
            "- Prioritize event/time-of-day segmentation, volatility-adaptive exits, and explicit no-trade filters around high-ambiguity periods.",
            "- Consider MGC only after these MNQ lessons are encoded into the next plan and after confirming the new axis is not just another broad expansion.",
            "",
        ]
    )
    return "\n".join(lines)


def _candidate_count(results: pd.DataFrame) -> int:
    if "candidate_id" in results.columns:
        return int(results["candidate_id"].nunique())
    return len(results)


def _label_counts(results: pd.DataFrame, label_column: str) -> dict[str, int]:
    if label_column not in results.columns:
        return {}
    return {str(label): int(count) for label, count in results[label_column].value_counts().to_dict().items()}


def _survivor_count(results: pd.DataFrame) -> int:
    if "phase6b_label" not in results.columns:
        return 0
    labels = results["phase6b_label"].fillna("").astype(str)
    return int(labels.isin(["prefilter_survivor", "watchlist_needs_walk_forward"]).sum())


def _candidate_table(
    phase_name: str,
    results: pd.DataFrame,
    rank_column: str,
    label_column: str,
    score_column: str,
    notes_column: str,
) -> list[str]:
    lines = [f"### {phase_name}", ""]
    if results.empty:
        lines.append("No candidates were available.")
        return lines
    lines.extend(["| Rank | Candidate | Family | Label | Score | Net PnL | 4-Tick Slip | Notes |", "| ---: | --- | --- | --- | ---: | ---: | ---: | --- |"])
    ranked = results.copy()
    if rank_column in ranked.columns:
        ranked = ranked.sort_values(rank_column)
    for fallback_rank, (_, row) in enumerate(ranked.head(5).iterrows(), start=1):
        rank = int(row.get(rank_column, fallback_rank))
        candidate = row.get("candidate_id", "")
        family = row.get("family", "")
        label = row.get(label_column, "")
        score = _float(row.get(score_column, 0.0))
        net = _float(row.get("net_pnl", 0.0))
        slip = _float(row.get("slippage_4_ticks_net_pnl", 0.0))
        notes = row.get(notes_column, "")
        lines.append(f"| {rank} | `{candidate}` | {family} | {label} | {score:.2f} | ${net:.2f} | ${slip:.2f} | {notes} |")
    return lines


def _failure_mode_table(failure_modes: pd.DataFrame) -> list[str]:
    if failure_modes.empty:
        return ["No semicolon-delimited failure notes were present."]
    lines = ["| Failure Mode | Count |", "| --- | ---: |"]
    for failure_mode, row in failure_modes.head(12).iterrows():
        lines.append(f"| {failure_mode} | {int(row['count'])} |")
    return lines


def _failure_category_table(failure_categories: pd.DataFrame) -> list[str]:
    if failure_categories.empty:
        return ["No failure categories were available."]
    lines = ["| Failure Category | Count |", "| --- | ---: |"]
    for failure_category, row in failure_categories.iterrows():
        lines.append(f"| {failure_category} | {int(row['count'])} |")
    return lines


def _failure_category(failure_mode: str) -> str:
    lowered = failure_mode.lower()
    if "concentration" in lowered:
        return "concentration"
    if "slippage" in lowered or "cost" in lowered:
        return "cost_slippage"
    if "drawdown" in lowered:
        return "drawdown"
    if "validation" in lowered or "holdout" in lowered or "split" in lowered:
        return "split_instability"
    if "ambiguity" in lowered or "same-bar" in lowered:
        return "ambiguity"
    return "other"


def _float(value: object) -> float:
    try:
        out = float(value)
    except (TypeError, ValueError):
        return 0.0
    if pd.isna(out):
        return 0.0
    return out
