from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

import pandas as pd


@dataclass(frozen=True)
class Phase7DPolicy:
    funded_quantity: int
    daily_profit_target: float | None
    daily_loss_lockout: float | None

    @property
    def policy_id(self) -> str:
        profit = "none" if self.daily_profit_target is None else _fmt_num(self.daily_profit_target)
        loss = "none" if self.daily_loss_lockout is None else _fmt_num(self.daily_loss_lockout)
        return f"q{self.funded_quantity}_pt{profit}_ll{loss}"


@dataclass(frozen=True)
class Phase7DConfig:
    legacy_start: str = "2025-12-29"
    legacy_end: str = "2026-06-26"
    source_quantity: int = 1
    funded_quantities: tuple[int, ...] = (1, 2)
    daily_profit_targets: tuple[float | None, ...] = (None, 200.0)
    daily_loss_lockouts: tuple[float | None, ...] = (None, 300.0)
    evaluation_target: float = 2_000.0
    max_loss_limit: float = 1_000.0
    payout_threshold: float = 500.0
    trader_profit_split: float = 0.50
    min_funded_profit_days: int = 5

    def validate(self) -> "Phase7DConfig":
        if self.source_quantity <= 0:
            raise ValueError("source_quantity must be positive")
        if any(quantity <= 0 for quantity in self.funded_quantities):
            raise ValueError("funded_quantities must be positive")
        if self.evaluation_target <= 0 or self.max_loss_limit <= 0 or self.payout_threshold <= 0:
            raise ValueError("evaluation_target, max_loss_limit, and payout_threshold must be positive")
        if not 0 < self.trader_profit_split <= 1:
            raise ValueError("trader_profit_split must be in (0, 1]")
        return self


def phase7d_policy_grid(config: Phase7DConfig = Phase7DConfig()) -> list[Phase7DPolicy]:
    config.validate()
    return [
        Phase7DPolicy(quantity, profit_target, loss_lockout)
        for quantity in config.funded_quantities
        for profit_target in config.daily_profit_targets
        for loss_lockout in config.daily_loss_lockouts
    ]


def run_phase7d_payout_diagnostic(trade_log_path: Path, config: Phase7DConfig = Phase7DConfig()) -> pd.DataFrame:
    config.validate()
    if not trade_log_path.exists():
        raise FileNotFoundError(f"Phase 7D requires Phase 7B trade log at {trade_log_path}")
    trades = pd.read_csv(trade_log_path)
    if trades.empty:
        return pd.DataFrame()
    required = {"combo_id", "trading_session", "net_pnl", "same_bar_stop_target_ambiguity", "component_family"}
    missing = sorted(required.difference(trades.columns))
    if missing:
        raise ValueError(f"Phase 7D trade log is missing required columns: {missing}")
    scoped = trades.copy()
    scoped["trading_session"] = pd.to_datetime(scoped["trading_session"]).dt.date.astype(str)
    scoped = scoped[(scoped["trading_session"] >= config.legacy_start) & (scoped["trading_session"] <= config.legacy_end)]
    rows: list[dict[str, Any]] = []
    for combo_id, combo_trades in scoped.groupby("combo_id", sort=True):
        for policy in phase7d_policy_grid(config):
            rows.append(_replay_combo_policy(str(combo_id), combo_trades, policy, config))
    if not rows:
        return pd.DataFrame()
    out = pd.DataFrame(rows)
    out = out.sort_values(["success", "estimated_payout", "max_loss_remaining_at_payout", "final_pnl"], ascending=[False, False, False, False]).reset_index(drop=True)
    out.insert(0, "phase7d_rank", range(1, len(out) + 1))
    return out


def render_phase7d_report(results: pd.DataFrame, config: Phase7DConfig, results_path: Path, report_path: Path) -> str:
    lines = [
        "# Phase 7D MGC Payout-Path / Matched-Window Diagnostic",
        "",
        "Generated by: `./.venv/Scripts/python.exe scripts/run_phase7d_payout_diagnostic.py`",
        "",
        "## Scope And Guardrails",
        "",
        "- Research/simulation only. No live trading, broker adapters, API-key storage, webhooks, order routing, or automated execution were added.",
        "- Phase 7D replays existing Phase 7B deterministic trade logs through a simplified payout-path diagnostic.",
        "- This diagnostic isolates objective/date-window/phase-policy drift; it does not override Phase 7B rejection labels or promote paper trading.",
        "",
        "## Configuration",
        "",
        f"- Matched legacy window: `{config.legacy_start}` through `{config.legacy_end}`",
        f"- Funded quantities tested: `{config.funded_quantities}`",
        f"- Daily profit targets: `{config.daily_profit_targets}`",
        f"- Daily loss lockouts: `{config.daily_loss_lockouts}`",
        f"- Evaluation target / max loss / payout threshold: `${config.evaluation_target:.2f}` / `${config.max_loss_limit:.2f}` / `${config.payout_threshold:.2f}`",
        f"- Trader profit split used for estimated payout: `{config.trader_profit_split:.2f}`",
        "",
        "## Outputs",
        "",
        f"- Results CSV: `{results_path}`",
        f"- Report: `{report_path}`",
        "",
        "## Results Summary",
        "",
        f"- Rows scored: `{len(results)}`",
        f"- Successful payout-path rows: `{int(results['success'].sum()) if not results.empty and 'success' in results else 0}`",
        "",
        "| Rank | Combo | Policy | Success | Eval Pass | Payout Date | Est. Payout | Final PnL | Max-Loss Cushion | Breach Date | Ambiguous Trades | Notes |",
        "| ---: | --- | --- | --- | --- | --- | ---: | ---: | ---: | --- | ---: | --- |",
    ]
    if not results.empty:
        for _, row in results.head(12).iterrows():
            lines.append(
                f"| {int(row['phase7d_rank'])} | `{row['combo_id']}` | `{row['policy_id']}` | {bool(row['success'])} | {row.get('evaluation_pass_date', '')} | {row.get('payout_date', '')} | ${row['estimated_payout']:.2f} | ${row['final_pnl']:.2f} | ${row['max_loss_remaining_at_payout']:.2f} | {row.get('breach_date', '')} | {int(row['same_bar_stop_target_ambiguity_count'])} | {row['phase7d_notes']} |"
            )
    lines.extend(
        [
            "",
            "## Interpretation",
            "",
            "A success here only means the rejected Phase 7B combo can be made to hit a simplified payout-path objective on the matched legacy window. It remains blocked by Phase 7B robustness failures, especially 4-tick slippage, drawdown, concentration, validation/holdout, and same-bar ambiguity.",
            "",
            "## Repro Command",
            "",
            "```bash",
            "./.venv/Scripts/python.exe scripts/run_phase7d_payout_diagnostic.py",
            "```",
            "",
        ]
    )
    return "\n".join(lines)


def _replay_combo_policy(combo_id: str, trades: pd.DataFrame, policy: Phase7DPolicy, config: Phase7DConfig) -> dict[str, Any]:
    day_pnl = trades.groupby("trading_session", sort=True)["net_pnl"].sum()
    multiplier = policy.funded_quantity / config.source_quantity
    cumulative = 0.0
    peak = 0.0
    evaluation_pass_date = ""
    payout_date = ""
    breach_date = ""
    phase = "evaluation"
    funded_profit_days = 0
    payout_cycle_pnl = 0.0
    max_loss_remaining_at_payout = 0.0
    lockout_day_count = 0
    profit_target_lockout_count = 0
    loss_lockout_count = 0
    processed_days = 0
    for session, raw_pnl in day_pnl.items():
        processed_days += 1
        scaled = float(raw_pnl) * multiplier
        adjusted = _apply_daily_policy(scaled, policy)
        if adjusted != scaled:
            lockout_day_count += 1
            if policy.daily_profit_target is not None and scaled > policy.daily_profit_target:
                profit_target_lockout_count += 1
            if policy.daily_loss_lockout is not None and scaled < -abs(policy.daily_loss_lockout):
                loss_lockout_count += 1
        cumulative += adjusted
        peak = max(peak, cumulative)
        drawdown = peak - cumulative
        if drawdown >= config.max_loss_limit:
            breach_date = str(session)
            break
        if phase == "evaluation" and cumulative >= config.evaluation_target:
            phase = "funded"
            evaluation_pass_date = str(session)
            payout_cycle_pnl = 0.0
            funded_profit_days = 0
            continue
        if phase == "funded":
            payout_cycle_pnl += adjusted
            if adjusted > 0:
                funded_profit_days += 1
            estimated_payout = max(payout_cycle_pnl * config.trader_profit_split, 0.0)
            if estimated_payout >= config.payout_threshold and funded_profit_days >= config.min_funded_profit_days:
                payout_date = str(session)
                max_loss_remaining_at_payout = max(config.max_loss_limit - drawdown, 0.0)
                break
    estimated_payout = max(payout_cycle_pnl * config.trader_profit_split, 0.0) if payout_date else 0.0
    success = bool(payout_date)
    return {
        "combo_id": combo_id,
        "policy_id": policy.policy_id,
        "funded_quantity": policy.funded_quantity,
        "daily_profit_target": "none" if policy.daily_profit_target is None else policy.daily_profit_target,
        "daily_loss_lockout": "none" if policy.daily_loss_lockout is None else policy.daily_loss_lockout,
        "success": success,
        "evaluation_pass_date": evaluation_pass_date,
        "payout_date": payout_date,
        "estimated_payout": float(estimated_payout),
        "processed_days": processed_days,
        "max_loss_remaining_at_payout": float(max_loss_remaining_at_payout),
        "final_pnl": float(cumulative),
        "breach_date": breach_date,
        "lockout_day_count": int(lockout_day_count),
        "profit_target_lockout_count": int(profit_target_lockout_count),
        "loss_lockout_count": int(loss_lockout_count),
        "same_bar_stop_target_ambiguity_count": int(trades["same_bar_stop_target_ambiguity"].fillna(0).sum()),
        "component_trade_counts": trades["component_family"].value_counts().to_json(),
        "phase7d_notes": _phase7d_notes(success, evaluation_pass_date, payout_date, breach_date, trades),
    }


def _apply_daily_policy(daily_pnl: float, policy: Phase7DPolicy) -> float:
    adjusted = daily_pnl
    if policy.daily_profit_target is not None:
        adjusted = min(adjusted, float(policy.daily_profit_target))
    if policy.daily_loss_lockout is not None:
        adjusted = max(adjusted, -abs(float(policy.daily_loss_lockout)))
    return adjusted


def _phase7d_notes(success: bool, evaluation_pass_date: str, payout_date: str, breach_date: str, trades: pd.DataFrame) -> str:
    notes: list[str] = []
    if success:
        notes.append("hits simplified payout-path objective on matched window")
    elif breach_date:
        notes.append("max-loss breach before payout objective")
    elif not evaluation_pass_date:
        notes.append("does not pass evaluation target")
    else:
        notes.append("passes evaluation but does not reach payout threshold")
    ambiguity = int(trades["same_bar_stop_target_ambiguity"].fillna(0).sum())
    if ambiguity:
        notes.append("same-bar ambiguity remains; still not promotable")
    return "; ".join(notes)


def _fmt_num(value: float) -> str:
    return str(int(value)) if float(value).is_integer() else str(value).replace(".", "p")
