from __future__ import annotations

from collections import Counter
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Mapping

import pandas as pd


@dataclass(frozen=True)
class Phase8BConfig:
    phase7c_path: Path = Path("outputs/phase7c_assumption_drift.csv")
    phase7d_path: Path = Path("outputs/phase7d_payout_diagnostic_results.csv")
    phase8a_path: Path = Path("outputs/phase8a_mgc_clean_family_results.csv")
    phase8a_manifest_path: Path = Path("artifacts/phase8a_mgc_clean_family/phase8a-r1-smoke/manifest.json")
    symbol: str = "MGC"
    overtrading_active_session_threshold: float = 0.75
    overtrading_trade_threshold: int = 500
    concentration_threshold: float = 0.50
    drawdown_limit: float = -1_000.0


@dataclass(frozen=True)
class Phase8BResult:
    failure_summary: pd.DataFrame
    phase7c_rows: int
    phase7c_high_severity_count: int
    phase7d_rows: int
    phase7d_success_count: int
    phase8a_scored_count: int
    phase8a_selected_specs_count: int
    phase8a_label_counts: dict[str, int]
    recommended_next_step: str
    decision: str

    def to_manifest_payload(self) -> dict[str, Any]:
        return {
            "phase7c_rows": self.phase7c_rows,
            "phase7c_high_severity_count": self.phase7c_high_severity_count,
            "phase7d_rows": self.phase7d_rows,
            "phase7d_success_count": self.phase7d_success_count,
            "phase8a_scored_count": self.phase8a_scored_count,
            "phase8a_selected_specs_count": self.phase8a_selected_specs_count,
            "phase8a_label_counts": self.phase8a_label_counts,
            "recommended_next_step": self.recommended_next_step,
            "decision": self.decision,
            "top_failure_categories": self.failure_summary.head(5).to_dict(orient="records"),
        }


def synthesize_phase8b_failures(
    phase7c: pd.DataFrame,
    phase7d: pd.DataFrame,
    phase8a: pd.DataFrame,
    *,
    phase8a_manifest: Mapping[str, Any] | None = None,
    config: Phase8BConfig = Phase8BConfig(),
) -> Phase8BResult:
    phase8a_manifest = phase8a_manifest or {}
    phase7c_counts = _phase7c_counts(phase7c)
    phase7d_counts = _note_counts(phase7d, "phase7d_notes")
    phase8a_counts = _phase8a_counts(phase8a, config)
    categories = sorted(set(phase7c_counts) | set(phase7d_counts) | set(phase8a_counts))
    rows = []
    for category in categories:
        phase7c_count = phase7c_counts.get(category, 0)
        phase7d_count = phase7d_counts.get(category, 0)
        phase8a_count = phase8a_counts.get(category, 0)
        total = phase7c_count + phase7d_count + phase8a_count
        rows.append(
            {
                "failure_category": category,
                "phase7c_count": int(phase7c_count),
                "phase7d_count": int(phase7d_count),
                "phase8a_count": int(phase8a_count),
                "total_count": int(total),
                "interpretation": _category_interpretation(category),
            }
        )
    failure_summary = pd.DataFrame(
        rows,
        columns=["failure_category", "phase7c_count", "phase7d_count", "phase8a_count", "total_count", "interpretation"],
    ).sort_values(["total_count", "failure_category"], ascending=[False, True], ignore_index=True)

    label_counts = _phase8a_label_counts(phase8a, phase8a_manifest)
    selected_specs_count = _manifest_int(phase8a_manifest, "selected_specs_count", len(phase8a))
    decision = (
        "Stop entry-variant grinding; use Phase 8B evidence to design pre-entry no-trade/session-selection filters "
        "before spending more MGC compute."
    )
    return Phase8BResult(
        failure_summary=failure_summary,
        phase7c_rows=int(len(phase7c)),
        phase7c_high_severity_count=_high_severity_count(phase7c),
        phase7d_rows=int(len(phase7d)),
        phase7d_success_count=_success_count(phase7d),
        phase8a_scored_count=int(len(phase8a)),
        phase8a_selected_specs_count=selected_specs_count,
        phase8a_label_counts=label_counts,
        recommended_next_step="phase8c_no_trade_session_filters",
        decision=decision,
    )


def render_phase8b_report(
    result: Phase8BResult,
    config: Phase8BConfig,
    *,
    summary_path: Path,
    report_path: Path,
    run_artifact_dir: Path | None = None,
) -> str:
    lines = [
        "# Phase 8B MGC Failure Synthesis Report",
        "",
        "Generated by: `./.venv/Scripts/python.exe scripts/run_phase8b_failure_synthesis.py`",
        "",
        "## Scope And Guardrails",
        "",
        "- Research/simulation only. No live trading, broker adapters, API-key storage, webhooks, order routing, or automated execution were added.",
        "- Phase 8B synthesizes already-generated Phase 7C, Phase 7D, and Phase 8A artifacts; it does not change strategy logic or promotion gates.",
        "- Candidate labels remain research labels only; no paper-test or live-trading promotion is made here.",
        "",
        "## Source Artifacts",
        "",
        f"- Phase 7C drift audit: `{config.phase7c_path.as_posix()}`",
        f"- Phase 7D payout diagnostic: `{config.phase7d_path.as_posix()}`",
        f"- Phase 8A clean-family results: `{config.phase8a_path.as_posix()}`",
        f"- Phase 8A manifest: `{config.phase8a_manifest_path.as_posix()}`",
        "",
        "## Current Evidence Snapshot",
        "",
        f"- Phase 7C high-severity drift axes: `{result.phase7c_high_severity_count}` / `{result.phase7c_rows}`",
        f"- Phase 7D successful payout-path rows: `{result.phase7d_success_count} / {result.phase7d_rows}`",
        f"- Phase 8A scored clean-family specs: `{result.phase8a_scored_count} / {result.phase8a_selected_specs_count}`",
        f"- Phase 8A labels: `{result.phase8a_label_counts}`",
        "",
        "## Failure Category Totals",
        "",
        "| Category | Total | Phase 7C | Phase 7D | Phase 8A | Interpretation |",
        "| --- | ---: | ---: | ---: | ---: | --- |",
    ]
    for _, row in result.failure_summary.iterrows():
        lines.append(
            f"| {row['failure_category']} | {int(row['total_count'])} | {int(row['phase7c_count'])} | "
            f"{int(row['phase7d_count'])} | {int(row['phase8a_count'])} | {row['interpretation']} |"
        )
    lines.extend(
        [
            "",
            "## Decision",
            "",
            f"- Recommended next step: `{result.recommended_next_step}`.",
            f"- Decision: {result.decision}",
            "- Do not keep widening entry families until a no-trade/session-selection filter is explicitly tested with pre-entry information only.",
            "",
            "## Outputs",
            "",
            f"- Failure summary CSV: `{summary_path.as_posix()}`",
            f"- Report: `{report_path.as_posix()}`",
        ]
    )
    if run_artifact_dir is not None:
        lines.append(f"- Run-scoped artifacts: `{run_artifact_dir.as_posix()}`")
    lines.extend(
        [
            "",
            "## Repro Command",
            "",
            "```bash",
            "./.venv/Scripts/python.exe scripts/run_phase8b_failure_synthesis.py",
            "```",
            "",
        ]
    )
    return "\n".join(lines)


def _phase7c_counts(phase7c: pd.DataFrame) -> Counter[str]:
    counter: Counter[str] = Counter()
    for _, row in phase7c.iterrows():
        axis_text = " ".join(str(row.get(column, "")) for column in ("axis", "drift", "recommended_action"))
        category = _category_for_text(axis_text)
        if category:
            counter[category] += 1
    return counter


def _note_counts(results: pd.DataFrame, notes_column: str) -> Counter[str]:
    counter: Counter[str] = Counter()
    if notes_column not in results.columns:
        return counter
    for raw_notes in results[notes_column].fillna(""):
        for note in str(raw_notes).split(";"):
            category = _category_for_text(note)
            if category:
                counter[category] += 1
    return counter


def _phase8a_counts(phase8a: pd.DataFrame, config: Phase8BConfig) -> Counter[str]:
    counter = _note_counts(phase8a, "phase8a_notes")
    if "risk_notes" in phase8a.columns:
        counter.update(_note_counts(phase8a, "risk_notes"))
    for _, row in phase8a.iterrows():
        if _float(row.get("net_pnl")) < 0:
            counter["negative_expectancy"] += 1
        if _float(row.get("slippage_4_ticks_net_pnl")) < 0:
            counter["cost_slippage"] += 1
        if _float(row.get("active_session_pct")) >= config.overtrading_active_session_threshold or _float(row.get("trades")) >= config.overtrading_trade_threshold:
            counter["overtrading"] += 1
        if _float(row.get("max_drawdown")) <= config.drawdown_limit:
            counter["drawdown"] += 1
        if _float(row.get("best_day_concentration")) >= config.concentration_threshold:
            counter["concentration"] += 1
        if _float(row.get("best_trade_concentration")) >= config.concentration_threshold:
            counter["concentration"] += 1
        if _float(row.get("same_bar_stop_target_ambiguity_count")) > 0:
            counter["ambiguity"] += 1
        if _float(row.get("validation_pnl")) < 0:
            counter["split_instability"] += 1
        if _float(row.get("holdout_pnl")) < 0:
            counter["split_instability"] += 1
    return counter


def _category_for_text(text: object) -> str:
    lowered = str(text).lower()
    if not lowered.strip():
        return ""
    if "not promotable" in lowered:
        return ""
    if "concentration" in lowered:
        return "concentration"
    if "slippage" in lowered or "cost" in lowered:
        return "cost_slippage"
    if "drawdown" in lowered or "max-loss" in lowered or "max loss" in lowered:
        return "drawdown"
    if "same-bar" in lowered or "ambiguity" in lowered:
        return "ambiguity"
    if "validation" in lowered or "holdout" in lowered or "split" in lowered:
        return "split_instability"
    if "data window" in lowered or "date-window" in lowered or "matched-window" in lowered:
        return "data_window_drift"
    if "objective" in lowered or "evaluation" in lowered or "payout" in lowered:
        return "objective_drift"
    if "phase" in lowered or "lockout" in lowered or "policy" in lowered:
        return "policy_drift"
    if "negative net" in lowered or "negative pnl" in lowered:
        return "negative_expectancy"
    return "other"


def _category_interpretation(category: str) -> str:
    return {
        "ambiguity": "Intrabar uncertainty remains a research blocker, not a tuning problem.",
        "concentration": "PnL is too dependent on one day/trade; require distribution filters before promotion.",
        "cost_slippage": "Costs/stress erase the apparent edge; fewer higher-quality trades are needed.",
        "data_window_drift": "Legacy and current windows differ; avoid broadening until provenance is explicit.",
        "drawdown": "Loss path breaches strict risk limits before any payout/promotion case is credible.",
        "negative_expectancy": "Raw net performance is negative before advanced validation.",
        "objective_drift": "Payout-style objectives and robustness objectives are not equivalent.",
        "overtrading": "Candidates are active in too many sessions; next work should decide when not to trade.",
        "policy_drift": "Risk policy assumptions changed enough to require diagnostic isolation.",
        "split_instability": "Validation/holdout weakness means the signal is not stable enough for promotion.",
        "other": "Unclassified failure evidence that should be inspected before broadening search.",
    }.get(category, "Unclassified failure evidence.")


def _high_severity_count(phase7c: pd.DataFrame) -> int:
    if "severity" not in phase7c.columns:
        return 0
    return int((phase7c["severity"].fillna("").astype(str).str.lower() == "high").sum())


def _success_count(phase7d: pd.DataFrame) -> int:
    if "success" not in phase7d.columns:
        return 0
    values = phase7d["success"]
    if values.dtype == bool:
        return int(values.sum())
    return int(values.fillna(False).astype(str).str.lower().isin(["true", "1", "yes"]).sum())


def _phase8a_label_counts(phase8a: pd.DataFrame, manifest: Mapping[str, Any]) -> dict[str, int]:
    manifest_counts = manifest.get("label_counts")
    if isinstance(manifest_counts, Mapping):
        return {str(key): int(value) for key, value in manifest_counts.items()}
    if "phase8a_label" not in phase8a.columns:
        return {}
    return {str(key): int(value) for key, value in phase8a["phase8a_label"].fillna("missing").value_counts().sort_index().to_dict().items()}


def _manifest_int(manifest: Mapping[str, Any], key: str, default: int) -> int:
    try:
        return int(manifest.get(key, default))
    except (TypeError, ValueError):
        return int(default)


def _float(value: object) -> float:
    try:
        out = float(value)
    except (TypeError, ValueError):
        return 0.0
    if pd.isna(out):
        return 0.0
    return out
