from __future__ import annotations

from collections import Counter

import pandas as pd


def summarize_failure_modes(results: pd.DataFrame) -> pd.DataFrame:
    counter: Counter[str] = Counter()
    notes = results.get("phase6a_notes", pd.Series(dtype=str))
    for raw_notes in notes.fillna(""):
        for note in str(raw_notes).split(";"):
            cleaned = note.strip()
            if cleaned:
                counter[cleaned] += 1
    rows = [{"failure_mode": mode, "count": count} for mode, count in counter.items()]
    if not rows:
        return pd.DataFrame(columns=["failure_mode", "count"]).set_index("failure_mode")
    return pd.DataFrame(rows).sort_values(["count", "failure_mode"], ascending=[False, True]).set_index("failure_mode")


def render_failure_analysis_report(results: pd.DataFrame, failure_modes: pd.DataFrame) -> str:
    label_counts = results["phase6a_label"].value_counts().to_dict() if "phase6a_label" in results.columns else {}
    scored_count = int(results["candidate_id"].nunique()) if "candidate_id" in results.columns else len(results)
    lines = [
        "# Phase 6A Failure-Mode Analysis Report",
        "",
        "Generated by: `./.venv/Scripts/python.exe scripts/run_phase6a_failure_analysis.py`",
        "",
        "## Scope And Guardrails",
        "",
        "- Research/simulation only. No live trading, broker adapters, API-key storage, webhooks, order routing, or automated execution were added.",
        "- Analysis uses only completed Phase 6A local-output CSV data derived from local CSV files under `data/raw`.",
        "- Phase 6A remained MNQ-only; this report captures MNQ lessons before Phase 6B search design.",
        "",
        "## Summary",
        "",
        f"- Analyzed {scored_count} scored Phase 6A candidates.",
        f"- Label counts: `{label_counts}`",
        "- All candidates remain research candidates only; none are approved for paper trading without deeper validation.",
        "",
        "## Failure Modes",
        "",
    ]
    if failure_modes.empty:
        lines.append("No semicolon-delimited Phase 6A failure notes were present.")
    else:
        lines.extend(["| Failure Mode | Count |", "| --- | ---: |"])
        for failure_mode, row in failure_modes.iterrows():
            lines.append(f"| {failure_mode} | {int(row['count'])} |")
    lines.extend(["", "## Top Ranked Phase 6A Candidates", ""])
    if results.empty:
        lines.append("No Phase 6A candidates were available.")
    else:
        lines.extend(["| Rank | Candidate | Label | Score | Net PnL | 4-Tick Slip | Notes |", "| ---: | --- | --- | ---: | ---: | ---: | --- |"])
        for _, row in results.head(10).iterrows():
            rank = int(row.get("phase6a_rank", 0))
            candidate = row.get("candidate_id", "")
            label = row.get("phase6a_label", "")
            score = float(row.get("phase6a_score", 0.0))
            net_pnl = float(row.get("net_pnl", 0.0))
            slip_pnl = float(row.get("slippage_4_ticks_net_pnl", 0.0))
            notes = row.get("phase6a_notes", "")
            lines.append(f"| {rank} | `{candidate}` | {label} | {score:.2f} | ${net_pnl:.2f} | ${slip_pnl:.2f} | {notes} |")
    lines.extend(
        [
            "",
            "## Interpretation And Next Step",
            "",
            "- Phase 6B should prioritize ambiguity/concentration reduction rather than broader blind expansion.",
            "- Useful next levers include one-trade-per-day enforcement, entry buffers beyond ambiguous levels, avoiding the open/close edge windows, and range/volatility filters that reduce low-quality triggers.",
            "- Do not expand beyond MNQ until these Phase 6A failure modes are reflected in the Phase 6B design.",
            "",
        ]
    )
    return "\n".join(lines)
