from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

import pandas as pd


@dataclass(frozen=True)
class Phase8EConfig:
    max_hypotheses: int = 40
    min_events: int = 50
    horizons: tuple[int, ...] = (15, 30, 60)
    max_backtest_candidates: int = 6


def run_phase8e_event_scout(queue: pd.DataFrame, data_by_symbol: dict[str, pd.DataFrame], config: Phase8EConfig = Phase8EConfig()) -> pd.DataFrame:
    rows = []
    for _, hypothesis in queue.head(config.max_hypotheses).iterrows():
        symbol = str(hypothesis["instrument"])
        rows.append(score_hypothesis_events(data_by_symbol.get(symbol, pd.DataFrame()), hypothesis.to_dict(), config))
    results = pd.DataFrame(rows)
    if results.empty:
        return results
    results = results.sort_values(["phase8e_score", "avg_forward_15m", "event_count"], ascending=[False, False, False]).reset_index(drop=True)
    candidate_mask = results["phase8e_label"].eq("backtest_candidate")
    candidate_indexes = results[candidate_mask].index.tolist()
    for index in candidate_indexes[config.max_backtest_candidates :]:
        results.loc[index, "phase8e_label"] = "needs_filter"
        results.loc[index, "phase8e_notes"] = str(results.loc[index, "phase8e_notes"]) + "; demoted by max diverse backtest-candidate cap"
    results.insert(0, "phase8e_rank", range(1, len(results) + 1))
    return results


def score_hypothesis_events(bars: pd.DataFrame, hypothesis: dict[str, Any], config: Phase8EConfig = Phase8EConfig()) -> dict[str, Any]:
    base = {
        "hypothesis_id": hypothesis["hypothesis_id"],
        "instrument": hypothesis["instrument"],
        "timeframe": int(hypothesis["timeframe"]),
        "side": hypothesis["side"],
        "family": hypothesis["family"],
    }
    if bars.empty:
        return _empty_event_row(base, "too_sparse", "no local bars for instrument")
    prepared = _prepare_bars(bars)
    event_positions = _event_positions(prepared, hypothesis)
    if not event_positions:
        return _empty_event_row(base, "too_sparse", "no qualifying events")
    direction = _direction_for_hypothesis(hypothesis)
    metrics = _forward_metrics(prepared, event_positions, direction, config.horizons)
    if metrics.empty or "forward_15m" not in metrics.columns:
        return _empty_event_row(base, "too_sparse", "no events with enough forward label history")
    event_count = int(len(metrics))
    if event_count < config.min_events:
        label = "too_sparse"
        notes = f"only {event_count} events; minimum is {config.min_events}"
    else:
        label, notes = _event_label_and_notes(metrics, event_count)
    score = _event_score(metrics, event_count, config.min_events)
    out = {
        **base,
        "event_count": event_count,
        "session_coverage": float(metrics["trading_session"].nunique() / prepared["trading_session"].nunique()) if prepared["trading_session"].nunique() else 0.0,
        "avg_forward_15m": round(float(metrics.get("forward_15m", pd.Series(dtype=float)).mean()), 6) if "forward_15m" in metrics else 0.0,
        "avg_forward_30m": round(float(metrics.get("forward_30m", pd.Series(dtype=float)).mean()), 6) if "forward_30m" in metrics else 0.0,
        "avg_forward_60m": round(float(metrics.get("forward_60m", pd.Series(dtype=float)).mean()), 6) if "forward_60m" in metrics else 0.0,
        "mfe_15m": round(float(metrics.get("mfe_15m", pd.Series(dtype=float)).mean()), 6) if "mfe_15m" in metrics else 0.0,
        "mae_15m": round(float(metrics.get("mae_15m", pd.Series(dtype=float)).mean()), 6) if "mae_15m" in metrics else 0.0,
        "directional_hit_rate_15m": round(float((metrics.get("forward_15m", pd.Series(dtype=float)) > 0).mean()), 6) if "forward_15m" in metrics else 0.0,
        "ambiguity_proxy": round(float((metrics.get("mfe_15m", pd.Series(dtype=float)) > 0).astype(int).add((metrics.get("mae_15m", pd.Series(dtype=float)) < 0).astype(int)).eq(2).mean()), 6) if "mfe_15m" in metrics and "mae_15m" in metrics else 0.0,
        "phase8e_score": round(score, 4),
        "phase8e_label": label,
        "phase8e_notes": notes,
    }
    return out


def render_phase8e_report(
    results: pd.DataFrame,
    config: Phase8EConfig,
    *,
    results_path: Path,
    report_path: Path,
    run_artifact_dir: Path | None = None,
) -> str:
    label_counts = results["phase8e_label"].value_counts().to_dict() if not results.empty and "phase8e_label" in results.columns else {}
    candidate_count = int((results["phase8e_label"] == "backtest_candidate").sum()) if not results.empty else 0
    lines = [
        "# Phase 8E Cheap Event-Study Scout",
        "",
        "Generated by: `./.venv/Scripts/python.exe scripts/run_phase8e_event_scout.py`",
        "",
        "## Scope And Guardrails",
        "",
        "- Research/simulation only. No live trading, broker adapters, order routing, API-key storage, webhooks, or automated execution were added.",
        "- Phase 8E measures forward behavior after deterministic events; it does not execute full strategy backtests or promote candidates.",
        "- Future returns are labels for research evaluation only, never signal inputs.",
        "",
        "## Summary",
        "",
        f"- Hypotheses scouted: `{len(results)}`",
        f"- Minimum events: `{config.min_events}`",
        f"- Backtest candidates: `{candidate_count}`",
        f"- Label counts: `{label_counts}`",
        "",
        "## Top Event Studies",
        "",
        "| Rank | Hypothesis | Instrument | TF | Side | Family | Label | Events | Avg 15m | Hit 15m | Score | Notes |",
        "| ---: | --- | --- | ---: | --- | --- | --- | ---: | ---: | ---: | ---: | --- |",
    ]
    for _, row in results.head(15).iterrows():
        lines.append(
            f"| {int(row['phase8e_rank']) if 'phase8e_rank' in row else ''} | `{row['hypothesis_id']}` | {row['instrument']} | {int(row['timeframe'])} | {row['side']} | "
            f"{row['family']} | {row['phase8e_label']} | {int(row['event_count'])} | {float(row['avg_forward_15m']):.4f} | "
            f"{float(row['directional_hit_rate_15m']) * 100:.1f}% | {float(row['phase8e_score']):.2f} | {row['phase8e_notes']} |"
        )
    lines.extend(
        [
            "",
            "## Decision Rule",
            "",
            "- Only `backtest_candidate` rows should be considered for a bounded Phase 8F probe.",
            "- `needs_filter` rows should go through no-trade/session filters before backtesting.",
            "- `too_sparse`, `reject_event`, and `ambiguous` rows should be parked unless new evidence appears.",
            "",
            "## Outputs",
            "",
            f"- Results CSV: `{results_path.as_posix()}`",
            f"- Report: `{report_path.as_posix()}`",
        ]
    )
    if run_artifact_dir is not None:
        lines.append(f"- Run-scoped artifacts: `{run_artifact_dir.as_posix()}`")
    lines.extend(["", "## Repro Command", "", "```bash", "./.venv/Scripts/python.exe scripts/run_phase8e_event_scout.py", "```", ""])
    return "\n".join(lines)


def _prepare_bars(bars: pd.DataFrame) -> pd.DataFrame:
    out = bars[bars.get("session_segment", "RTH").eq("RTH") if "session_segment" in bars.columns else pd.Series(True, index=bars.index)].copy()
    out["timestamp"] = pd.to_datetime(out["timestamp"])
    out = out.sort_values(["trading_session", "timestamp"]).reset_index(drop=True)
    out["bar_index"] = out.groupby("trading_session").cumcount()
    typical = (out["high"] + out["low"] + out["close"]) / 3.0
    pv = typical * out["volume"]
    out["vwap"] = pv.groupby(out["trading_session"]).cumsum() / out["volume"].groupby(out["trading_session"]).cumsum()
    daily = out.groupby("trading_session").agg(session_high=("high", "max"), session_low=("low", "min"), session_close=("close", "last"))
    out["prior_high"] = out["trading_session"].map(daily["session_high"].shift(1))
    out["prior_low"] = out["trading_session"].map(daily["session_low"].shift(1))
    out["prior_close"] = out["trading_session"].map(daily["session_close"].shift(1))
    return out


def _event_positions(bars: pd.DataFrame, hypothesis: dict[str, Any]) -> list[int]:
    family = str(hypothesis["family"])
    side = str(hypothesis["side"])
    positions: list[int] = []
    for _, day in bars.groupby("trading_session", sort=True):
        day_positions = day.index.to_list()
        if len(day_positions) < 20:
            continue
        if family in {"opening_range_breakout", "opening_range_fade"}:
            or_end = min(15, len(day_positions) - 1)
            opening = day.loc[day_positions[:or_end]]
            high = float(opening["high"].max())
            low = float(opening["low"].min())
            for pos in day_positions[or_end : min(len(day_positions), or_end + 90)]:
                close = float(bars.at[pos, "close"])
                if family == "opening_range_breakout" and ((side != "short_only" and close > high) or (side == "short_only" and close < low)):
                    positions.append(pos)
                if family == "opening_range_fade" and ((side != "short_only" and close < high) or (side == "short_only" and close > low)) and int(bars.at[pos, "bar_index"]) > or_end:
                    positions.append(pos)
        elif "vwap" in family:
            spread = day["close"] - day["vwap"]
            crosses = spread.mul(spread.shift(1)).lt(0).fillna(False)
            positions.extend(day.index[crosses].tolist())
        elif "prior_high_low" in family:
            subset = day.dropna(subset=["prior_high", "prior_low"])
            if subset.empty:
                continue
            if "breakout" in family:
                mask = (subset["close"] > subset["prior_high"]) | (subset["close"] < subset["prior_low"])
            else:
                mask = subset["high"].ge(subset["prior_high"]) | subset["low"].le(subset["prior_low"])
            positions.extend(subset.index[mask].tolist())
        elif family == "volatility_compression_breakout":
            ranges = day["high"] - day["low"]
            threshold = ranges.rolling(20, min_periods=5).quantile(0.25)
            mask = ranges.shift(1).lt(threshold.shift(1)) & day["close"].diff().abs().gt(ranges.rolling(20, min_periods=5).median())
            positions.extend(day.index[mask.fillna(False)].tolist())
        elif family == "time_of_day_momentum_reversion":
            positions.extend(day.index[day["bar_index"].isin([30, 60, 120, 300])].tolist())
        else:
            positions.extend(day.index[day["bar_index"].isin([30, 90, 180])].tolist())
    return sorted(set(int(pos) for pos in positions))


def _direction_for_hypothesis(hypothesis: dict[str, Any]) -> int:
    side = str(hypothesis["side"])
    if side == "short_only":
        return -1
    return 1


def _forward_metrics(bars: pd.DataFrame, positions: list[int], direction: int, horizons: tuple[int, ...]) -> pd.DataFrame:
    rows = []
    for pos in positions:
        if pos + min(horizons) >= len(bars):
            continue
        entry = float(bars.at[pos, "close"])
        row: dict[str, Any] = {"timestamp": bars.at[pos, "timestamp"], "trading_session": bars.at[pos, "trading_session"]}
        for horizon in horizons:
            if pos + horizon >= len(bars):
                continue
            future = bars.iloc[pos + 1 : pos + horizon + 1]
            if future.empty or future.iloc[-1]["trading_session"] != bars.at[pos, "trading_session"]:
                continue
            row[f"forward_{horizon}m"] = (float(future.iloc[-1]["close"]) - entry) * direction
            row[f"mfe_{horizon}m"] = (float(future["high"].max()) - entry) * direction if direction == 1 else (entry - float(future["low"].min()))
            row[f"mae_{horizon}m"] = (float(future["low"].min()) - entry) * direction if direction == 1 else (entry - float(future["high"].max()))
        if "forward_15m" in row:
            rows.append(row)
    return pd.DataFrame(rows)


def _event_label_and_notes(metrics: pd.DataFrame, event_count: int) -> tuple[str, str]:
    avg15 = float(metrics["forward_15m"].mean()) if "forward_15m" in metrics else 0.0
    hit15 = float((metrics["forward_15m"] > 0).mean()) if "forward_15m" in metrics else 0.0
    ambiguity = float(((metrics.get("mfe_15m", pd.Series(dtype=float)) > 0) & (metrics.get("mae_15m", pd.Series(dtype=float)) < 0)).mean()) if "mfe_15m" in metrics and "mae_15m" in metrics else 0.0
    if ambiguity > 0.75 and avg15 <= 0:
        return "ambiguous", "MFE and MAE frequently both appear inside the 15m label window"
    if avg15 > 0 and hit15 >= 0.52 and event_count >= 50:
        return "backtest_candidate", "positive 15m forward behavior with acceptable hit rate"
    if avg15 > 0:
        return "needs_filter", "positive average event behavior but hit rate or sample quality needs filtering"
    return "reject_event", "negative or flat forward event behavior"


def _event_score(metrics: pd.DataFrame, event_count: int, min_events: int) -> float:
    if metrics.empty:
        return -999.0
    avg15 = float(metrics["forward_15m"].mean()) if "forward_15m" in metrics else 0.0
    avg30 = float(metrics["forward_30m"].mean()) if "forward_30m" in metrics else 0.0
    hit15 = float((metrics["forward_15m"] > 0).mean()) if "forward_15m" in metrics else 0.0
    sample = min(event_count / max(min_events, 1), 2.0)
    return avg15 * 20.0 + avg30 * 10.0 + (hit15 - 0.5) * 30.0 + sample * 6.0


def _empty_event_row(base: dict[str, Any], label: str, notes: str) -> dict[str, Any]:
    return {
        **base,
        "event_count": 0,
        "session_coverage": 0.0,
        "avg_forward_15m": 0.0,
        "avg_forward_30m": 0.0,
        "avg_forward_60m": 0.0,
        "mfe_15m": 0.0,
        "mae_15m": 0.0,
        "directional_hit_rate_15m": 0.0,
        "ambiguity_proxy": 0.0,
        "phase8e_score": -999.0,
        "phase8e_label": label,
        "phase8e_notes": notes,
    }
