from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import pandas as pd

from .phase5n import _finite_float
from .strategy_spec import EntryRule, ExitRule, RiskRule, StrategySpec


@dataclass(frozen=True)
class Phase8FConfig:
    max_specs: int = 3
    min_trades: int = 60
    drawdown_limit: float = -2_500.0
    concentration_limit: float = 0.35


def select_phase8f_specs(event_results: pd.DataFrame, config: Phase8FConfig = Phase8FConfig()) -> list[StrategySpec]:
    candidates = event_results[event_results["phase8e_label"].eq("backtest_candidate")].sort_values("phase8e_score", ascending=False)
    specs: list[StrategySpec] = []
    used_keys: set[tuple[str, str]] = set()
    for _, row in candidates.iterrows():
        mapped = _spec_from_event_row(row)
        if mapped is None:
            continue
        key = (mapped.instrument, mapped.family)
        if key in used_keys:
            continue
        specs.append(mapped)
        used_keys.add(key)
        if len(specs) >= config.max_specs:
            break
    return specs


def rank_phase8f_results(candidate_summary: pd.DataFrame) -> pd.DataFrame:
    if candidate_summary.empty:
        return candidate_summary.copy()
    reusable = candidate_summary.drop(columns=[column for column in candidate_summary.columns if column.startswith(("phase5n_", "phase8f_"))], errors="ignore")
    rows: list[dict[str, Any]] = []
    for _, row in reusable.iterrows():
        out = row.to_dict()
        out["phase8f_score"] = _phase8f_score(out)
        out["phase8f_label"] = _phase8f_label(out)
        out["phase8f_notes"] = _phase8f_notes(out)
        rows.append(out)
    ranked = pd.DataFrame(rows).sort_values(["phase8f_score", "slippage_4_ticks_net_pnl", "net_pnl"], ascending=[False, False, False]).reset_index(drop=True)
    ranked.insert(0, "phase8f_rank", range(1, len(ranked) + 1))
    return ranked


def write_phase8f_specs(specs: list[StrategySpec], path: Path) -> None:
    path.write_text(json.dumps([json.loads(spec.to_json()) | {"canonical_id": spec.canonical_id()} for spec in specs], indent=2, sort_keys=True), encoding="utf-8")


def render_phase8f_report(
    results: pd.DataFrame,
    config: Phase8FConfig,
    *,
    results_path: Path,
    report_path: Path,
    run_artifact_dir: Path | None = None,
) -> str:
    label_counts = results["phase8f_label"].value_counts().to_dict() if not results.empty and "phase8f_label" in results.columns else {}
    lines = [
        "# Phase 8F Diverse Candidate Probe",
        "",
        "Generated by: `./.venv/Scripts/python.exe scripts/run_phase8f_diverse_candidate_probe.py`",
        "",
        "## Scope And Guardrails",
        "",
        "- Research/simulation only. No live trading, broker adapters, order routing, API-key storage, webhooks, or automated execution were added.",
        "- Phase 8F backtests at most `3` diverse event-study survivors; it is not a parameter sweep.",
        "- Candidate labels are diagnostic only and require walk-forward/concentration validation before paper-test consideration.",
        "",
        "## Summary",
        "",
        f"- Rows scored: `{len(results)}`",
        f"- Label counts: `{label_counts}`",
        "",
        "## Ranked Probe Results",
        "",
        "| Rank | Candidate | Instrument | Family | Label | Score | Net PnL | 4-Tick Stress | Trades | Active % | Max DD | Notes |",
        "| ---: | --- | --- | --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | --- |",
    ]
    for _, row in results.head(10).iterrows():
        lines.append(
            f"| {int(row['phase8f_rank'])} | `{row['candidate_id']}` | {row['instrument']} | {row['family']} | {row['phase8f_label']} | "
            f"{float(row['phase8f_score']):.2f} | ${float(row['net_pnl']):.2f} | ${float(row['slippage_4_ticks_net_pnl']):.2f} | "
            f"{int(row['trades'])} | {float(row['active_session_pct']) * 100:.1f}% | ${float(row['max_drawdown']):.2f} | {row['phase8f_notes']} |"
        )
    lines.extend(
        [
            "",
            "## Decision Rule",
            "",
            "- `phase8f_diverse_probe_candidate` means the idea deserves a later walk-forward-aware probe, not promotion.",
            "- `phase8f_watchlist_needs_filter` means raw behavior is positive but still needs no-trade/session filtering.",
            "- `rejected` means the bounded diverse probe failed strict first-pass gates.",
            "",
            "## Outputs",
            "",
            f"- Results CSV: `{results_path.as_posix()}`",
            f"- Report: `{report_path.as_posix()}`",
        ]
    )
    if run_artifact_dir is not None:
        lines.append(f"- Run-scoped artifacts: `{run_artifact_dir.as_posix()}`")
    lines.extend(["", "## Repro Command", "", "```bash", "./.venv/Scripts/python.exe scripts/run_phase8f_diverse_candidate_probe.py", "```", ""])
    return "\n".join(lines)


def _spec_from_event_row(row: pd.Series) -> StrategySpec | None:
    instrument = str(row["instrument"])
    timeframe = int(row["timeframe"])
    side_filter = _side_filter(str(row["side"]))
    family = str(row["family"])
    tick_params = _tick_params(instrument)
    risk = RiskRule("one_open_position", {"max_trades_per_day": 2, "side_filter": side_filter})
    if family == "vwap_pullback_continuation":
        return StrategySpec(
            instrument=instrument,
            family="vwap_pullback_continuation",
            timeframe=timeframe,
            entry=EntryRule("vwap_pullback", {"pullback_ref": "vwap", "pullback_ticks": tick_params["pullback_ticks"], "start_minute": 15, "min_slope_ticks": 0}),
            exit=ExitRule("fixed_ticks", {"stop_ticks": tick_params["stop_ticks"], "target_ticks": tick_params["target_ticks"]}),
            risk=risk,
            notes="Phase 8F diverse probe from Phase 8E event scout: VWAP pullback continuation.",
        ).validate()
    if family == "vwap_reclaim_rejection":
        mode = "both" if side_filter == "both" else ("reclaim" if side_filter == "long" else "rejection")
        return StrategySpec(
            instrument=instrument,
            family="vwap_reclaim_rejection",
            timeframe=timeframe,
            entry=EntryRule("vwap_cross", {"mode": mode}),
            exit=ExitRule("fixed_ticks", {"stop_ticks": tick_params["stop_ticks"], "target_ticks": tick_params["target_ticks"]}),
            risk=risk,
            notes="Phase 8F diverse probe from Phase 8E event scout: VWAP reclaim/rejection.",
        ).validate()
    if family == "opening_range_fade":
        return StrategySpec(
            instrument=instrument,
            family="opening_range_failure",
            timeframe=timeframe,
            entry=EntryRule("close_back_inside", {"or_minutes": 15, "target": "opposite", "min_range": tick_params["min_range"]}),
            exit=ExitRule("range_target", {"target": "opposite"}),
            risk=risk,
            notes="Phase 8F diverse probe from Phase 8E event scout: opening-range fade mapped to opening_range_failure.",
        ).validate()
    if family == "opening_range_breakout":
        return StrategySpec(
            instrument=instrument,
            family="opening_range_breakout",
            timeframe=timeframe,
            entry=EntryRule("close_outside_range", {"or_minutes": 15, "min_range": tick_params["min_range"]}),
            exit=ExitRule("r_multiple", {"target": "1R", "stop_mode": "half_range"}),
            risk=RiskRule("one_open_position", {"max_trades_per_day": 1, "side_filter": side_filter}),
            notes="Phase 8F diverse probe from Phase 8E event scout: opening-range breakout.",
        ).validate()
    return None


def _side_filter(side: str) -> str:
    if side == "long_only":
        return "long"
    if side == "short_only":
        return "short"
    return "both"


def _tick_params(instrument: str) -> dict[str, float | int]:
    if instrument == "MNQ":
        return {"stop_ticks": 40, "target_ticks": 60, "pullback_ticks": 8, "min_range": 10.0}
    return {"stop_ticks": 12, "target_ticks": 18, "pullback_ticks": 3, "min_range": 1.0}


def _phase8f_score(row: dict[str, Any]) -> float:
    net = _finite_float(row.get("net_pnl", 0.0), 0.0)
    stress = _finite_float(row.get("slippage_4_ticks_net_pnl", 0.0), 0.0)
    validation = _finite_float(row.get("validation_pnl", 0.0), 0.0)
    holdout = _finite_float(row.get("holdout_pnl", 0.0), 0.0)
    drawdown = _finite_float(row.get("max_drawdown", 0.0), 0.0)
    day = _finite_float(row.get("best_day_concentration", 1.0), 1.0)
    trade = _finite_float(row.get("best_trade_concentration", 1.0), 1.0)
    trades = _finite_float(row.get("trades", 0), 0.0)
    active = _finite_float(row.get("active_session_pct", 0.0), 0.0)
    score = 0.0
    score += max(min(net / 4_000.0, 2.0), -2.0) * 16.0
    score += max(min(stress / 4_000.0, 2.0), -2.0) * 26.0
    score += max(min(validation / 1_500.0, 2.0), -2.0) * 8.0
    score += max(min(holdout / 1_500.0, 2.0), -2.0) * 14.0
    score += min(trades / 150.0, 1.0) * 8.0
    score += min(active, 0.50) * 8.0
    score -= min(abs(drawdown) / 2_500.0, 2.0) * 16.0
    score -= max(day - 0.35, 0.0) * 150.0
    score -= max(trade - 0.25, 0.0) * 150.0
    return round(float(score), 4)


def _phase8f_label(row: dict[str, Any]) -> str:
    notes = _phase8f_notes(row)
    if not notes:
        return "phase8f_diverse_probe_candidate"
    if _finite_float(row.get("net_pnl", 0.0), 0.0) > 0 and _finite_float(row.get("slippage_4_ticks_net_pnl", 0.0), 0.0) > 0:
        return "phase8f_watchlist_needs_filter"
    return "rejected"


def _phase8f_notes(row: dict[str, Any], config: Phase8FConfig = Phase8FConfig()) -> str:
    notes: list[str] = []
    if _finite_float(row.get("net_pnl", 0.0), 0.0) <= 0:
        notes.append("negative net PnL")
    if _finite_float(row.get("slippage_4_ticks_net_pnl", 0.0), 0.0) <= 0:
        notes.append("fails 4-tick stress")
    if int(_finite_float(row.get("trades", 0), 0.0)) < config.min_trades:
        notes.append("too few trades")
    if _finite_float(row.get("max_drawdown", 0.0), 0.0) < config.drawdown_limit:
        notes.append("drawdown exceeds diverse-probe cap")
    if _finite_float(row.get("best_day_concentration", 1.0), 1.0) > config.concentration_limit:
        notes.append("one-day concentration risk")
    if _finite_float(row.get("best_trade_concentration", 1.0), 1.0) > config.concentration_limit:
        notes.append("one-trade concentration risk")
    if _finite_float(row.get("validation_pnl", 0.0), 0.0) < 0:
        notes.append("negative validation split")
    if _finite_float(row.get("holdout_pnl", 0.0), 0.0) < 0:
        notes.append("negative holdout split")
    return "; ".join(notes) if notes else "survives bounded diverse probe; requires walk-forward validation"
