from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

import pandas as pd

from .backtest import FLATTEN_TIME, split_sessions
from .instruments import InstrumentSpec, get_instrument
from .phase8e_event_scout import _direction_for_hypothesis, _event_positions, _prepare_bars
from .phase8f_diverse_candidate_probe import _side_filter, _tick_params


@dataclass(frozen=True)
class CalibrationVariant:
    stop_model: str
    target_model: str
    time_stop: int


@dataclass(frozen=True)
class Phase8GConfig:
    max_candidates: int = 3
    entry_delays: tuple[str, ...] = ("next_bar_open", "next_1m_close", "next_3m_close", "next_5m_close")
    variants: tuple[CalibrationVariant, ...] = (
        CalibrationVariant("none", "horizon_close", 15),
        CalibrationVariant("none", "horizon_close", 30),
        CalibrationVariant("fixed_ticks", "1R", 30),
        CalibrationVariant("fixed_ticks", "1.5R", 30),
    )
    concentration_limit: float = 0.35


def select_phase8g_candidates(event_results: pd.DataFrame, config: Phase8GConfig = Phase8GConfig()) -> pd.DataFrame:
    """Select a capped, diversified set of event-study positives for calibration."""
    if event_results.empty:
        return event_results.copy()
    required = {"phase8e_label", "phase8e_score", "instrument", "family", "hypothesis_id"}
    missing = required.difference(event_results.columns)
    if missing:
        raise ValueError(f"Phase 8G event results missing required columns: {sorted(missing)}")
    positives = event_results[event_results["phase8e_label"].eq("backtest_candidate")].sort_values("phase8e_score", ascending=False)
    selected = []
    used_keys: set[tuple[str, str]] = set()
    for _, row in positives.iterrows():
        key = (str(row["instrument"]), str(row["family"]))
        if key in used_keys:
            continue
        selected.append(row)
        used_keys.add(key)
        if len(selected) >= config.max_candidates:
            break
    return pd.DataFrame(selected).reset_index(drop=True)


def run_phase8g_calibration(event_results: pd.DataFrame, data_by_symbol: dict[str, pd.DataFrame], config: Phase8GConfig = Phase8GConfig()) -> pd.DataFrame:
    candidates = select_phase8g_candidates(event_results, config)
    rows: list[dict[str, Any]] = []
    for _, candidate in candidates.iterrows():
        symbol = str(candidate["instrument"])
        bars = data_by_symbol.get(symbol, pd.DataFrame())
        if bars.empty:
            continue
        prepared = _prepare_bars(bars)
        event_positions = _event_positions(prepared, candidate.to_dict())
        for entry_delay in config.entry_delays:
            for variant in config.variants:
                trades = _simulate_calibration_trades(prepared, candidate.to_dict(), event_positions, entry_delay, variant)
                rows.append(_summarize_calibration(candidate.to_dict(), event_positions, entry_delay, variant, trades, config))
    if not rows:
        return pd.DataFrame(columns=_result_columns())
    result = pd.DataFrame(rows)
    result = result.sort_values(["calibration_score", "slippage_4_ticks_net_pnl", "net_pnl"], ascending=[False, False, False]).reset_index(drop=True)
    result.insert(0, "phase8g_rank", range(1, len(result) + 1))
    return result[_result_columns(include_rank=True)]


def render_phase8g_report(
    results: pd.DataFrame,
    config: Phase8GConfig,
    *,
    results_path: Path,
    report_path: Path,
    run_artifact_dir: Path | None = None,
) -> str:
    label_counts = results["calibration_label"].value_counts().to_dict() if not results.empty and "calibration_label" in results.columns else {}
    lines = [
        "# Phase 8G Event-To-Execution Calibration",
        "",
        "Generated by: `./.venv/Scripts/python.exe scripts/run_phase8g_event_execution_calibration.py`",
        "",
        "## Scope And Guardrails",
        "",
        "- Research/simulation only. No live trading, broker adapters, order routing, API-key storage, webhooks, or automated execution were added.",
        "- Phase 8G explains where event-study edge disappears between event labels and simple executable assumptions.",
        "- Calibration rows are diagnostics, not paper-trading promotions.",
        "",
        "## Summary",
        "",
        f"- Calibration rows: `{len(results)}`",
        f"- Event candidates capped at: `{config.max_candidates}`",
        f"- Label counts: `{label_counts}`",
        "",
        "## Ranked Calibration Rows",
        "",
        "| Rank | Calibration | Hypothesis | Instrument | Family | Entry | Stop | Target | Time | Label | Net PnL | 4-Tick Stress | Trades | DD | Notes |",
        "| ---: | --- | --- | --- | --- | --- | --- | --- | ---: | --- | ---: | ---: | ---: | ---: | --- |",
    ]
    for _, row in results.head(20).iterrows():
        lines.append(
            f"| {int(row['phase8g_rank'])} | `{row['calibration_id']}` | `{row['hypothesis_id']}` | {row['instrument']} | {row['family']} | "
            f"{row['entry_delay']} | {row['stop_model']} | {row['target_model']} | {int(row['time_stop'])}m | {row['calibration_label']} | "
            f"${float(row['net_pnl']):.2f} | ${float(row['slippage_4_ticks_net_pnl']):.2f} | {int(row['executable_trade_count'])} | "
            f"${float(row['max_drawdown']):.2f} | {row['calibration_notes']} |"
        )
    lines.extend(
        [
            "",
            "## Decision Rule",
            "",
            "- If horizon-close rows are positive but fixed stop/target rows fail, design better deterministic exits before parameter sweeps.",
            "- If every realistic entry delay fails net or 4-tick stress, park the event family as timing/cost sensitive.",
            "- If ambiguity or concentration dominates, avoid same-bar stop/target geometries and require pre-entry filters before deeper backtests.",
            "",
            "## Outputs",
            "",
            f"- Results CSV: `{results_path.as_posix()}`",
            f"- Report: `{report_path.as_posix()}`",
        ]
    )
    if run_artifact_dir is not None:
        lines.append(f"- Run-scoped artifacts: `{run_artifact_dir.as_posix()}`")
    lines.extend(["", "## Repro Command", "", "```bash", "./.venv/Scripts/python.exe scripts/run_phase8g_event_execution_calibration.py", "```", ""])
    return "\n".join(lines)


def _simulate_calibration_trades(
    bars: pd.DataFrame,
    hypothesis: dict[str, Any],
    event_positions: list[int],
    entry_delay: str,
    variant: CalibrationVariant,
) -> pd.DataFrame:
    spec = get_instrument(str(hypothesis["instrument"]))
    side = "long" if _side_filter(str(hypothesis["side"])) != "short" else "short"
    direction = _direction_for_hypothesis(hypothesis)
    rows = []
    for event_pos in event_positions:
        trade = _simulate_one_trade(bars, event_pos, side, direction, entry_delay, variant, spec)
        if trade is not None:
            rows.append(trade)
    return pd.DataFrame(rows)


def _simulate_one_trade(
    bars: pd.DataFrame,
    event_pos: int,
    side: str,
    direction: int,
    entry_delay: str,
    variant: CalibrationVariant,
    spec: InstrumentSpec,
) -> dict[str, Any] | None:
    delay_bars, price_column = _entry_delay(entry_delay)
    entry_pos = event_pos + delay_bars
    if entry_pos >= len(bars):
        return None
    event_session = bars.at[event_pos, "trading_session"]
    if bars.at[entry_pos, "trading_session"] != event_session:
        return None
    entry_time = bars.at[entry_pos, "timestamp"]
    if entry_time.time() >= FLATTEN_TIME:
        return None
    entry_price = float(bars.at[entry_pos, price_column])
    exit_limit = min(entry_pos + int(variant.time_stop), len(bars) - 1)
    while exit_limit > entry_pos and bars.at[exit_limit, "trading_session"] != event_session:
        exit_limit -= 1
    if exit_limit <= entry_pos:
        return None

    stop_price, target_price = _stop_target_prices(entry_price, side, variant, spec)
    exit_price = float(bars.at[exit_limit, "close"])
    exit_time = bars.at[exit_limit, "timestamp"]
    exit_reason = "time_stop"
    same_bar_ambiguity = 0

    if variant.stop_model != "none" and target_price is not None and stop_price is not None:
        for pos in range(entry_pos, exit_limit + 1):
            row = bars.iloc[pos]
            if row["timestamp"].time() >= FLATTEN_TIME:
                exit_price = float(row["open"])
                exit_time = row["timestamp"]
                exit_reason = "time_flatten"
                break
            high = float(row["high"])
            low = float(row["low"])
            if side == "long":
                stop_hit = low <= stop_price
                target_hit = high >= target_price
            else:
                stop_hit = high >= stop_price
                target_hit = low <= target_price
            if stop_hit and target_hit:
                same_bar_ambiguity += 1
            if stop_hit:
                exit_price = stop_price
                exit_time = row["timestamp"]
                exit_reason = "stop"
                break
            if target_hit:
                exit_price = target_price
                exit_time = row["timestamp"]
                exit_reason = "target"
                break

    gross_pnl = (exit_price - entry_price) * direction * spec.point_value
    return {
        "event_time": bars.at[event_pos, "timestamp"],
        "entry_time": entry_time,
        "exit_time": exit_time,
        "trading_session": event_session,
        "side": side,
        "entry_price": entry_price,
        "exit_price": exit_price,
        "exit_reason": exit_reason,
        "gross_pnl": gross_pnl,
        "net_pnl": gross_pnl - spec.base_cost,
        "stress_net_pnl": gross_pnl - spec.stress_cost,
        "same_bar_ambiguity": same_bar_ambiguity,
    }


def _summarize_calibration(
    hypothesis: dict[str, Any],
    event_positions: list[int],
    entry_delay: str,
    variant: CalibrationVariant,
    trades: pd.DataFrame,
    config: Phase8GConfig,
) -> dict[str, Any]:
    base = {
        "calibration_id": _calibration_id(hypothesis, entry_delay, variant),
        "hypothesis_id": hypothesis["hypothesis_id"],
        "instrument": hypothesis["instrument"],
        "family": hypothesis["family"],
        "side": hypothesis["side"],
        "timeframe": int(hypothesis["timeframe"]),
        "entry_delay": entry_delay,
        "stop_model": variant.stop_model,
        "target_model": variant.target_model,
        "time_stop": int(variant.time_stop),
        "event_count": int(len(event_positions)),
        "executable_trade_count": int(len(trades)),
        "skipped_event_count": int(max(len(event_positions) - len(trades), 0)),
    }
    if trades.empty:
        out = {
            **base,
            "gross_pnl": 0.0,
            "net_pnl": 0.0,
            "slippage_4_ticks_net_pnl": 0.0,
            "validation_pnl": 0.0,
            "holdout_pnl": 0.0,
            "max_drawdown": 0.0,
            "best_day_concentration": 1.0,
            "best_trade_concentration": 1.0,
            "same_bar_stop_target_ambiguity_count": 0,
        }
        out["calibration_score"] = _calibration_score(out)
        out["calibration_label"] = "too_sparse"
        out["calibration_notes"] = "no executable trades after realistic entry-delay/session checks"
        return out

    sessions = sorted(trades["trading_session"].dropna().unique().tolist())
    split_map = split_sessions(sessions)
    split_pnl = trades.assign(split=trades["trading_session"].map(split_map)).groupby("split")["net_pnl"].sum()
    total_net = float(trades["net_pnl"].sum())
    out = {
        **base,
        "gross_pnl": round(float(trades["gross_pnl"].sum()), 4),
        "net_pnl": round(total_net, 4),
        "slippage_4_ticks_net_pnl": round(float(trades["stress_net_pnl"].sum()), 4),
        "validation_pnl": round(float(split_pnl.get("validation", 0.0)), 4),
        "holdout_pnl": round(float(split_pnl.get("holdout", 0.0)), 4),
        "max_drawdown": round(_max_drawdown(trades), 4),
        "best_day_concentration": round(_best_day_concentration(trades, total_net), 6),
        "best_trade_concentration": round(_best_trade_concentration(trades, total_net), 6),
        "same_bar_stop_target_ambiguity_count": int(trades["same_bar_ambiguity"].sum()),
    }
    out["calibration_score"] = _calibration_score(out)
    out["calibration_label"] = _calibration_label(out, config)
    out["calibration_notes"] = _calibration_notes(out, config)
    return out


def _entry_delay(entry_delay: str) -> tuple[int, str]:
    if entry_delay == "next_bar_open":
        return 1, "open"
    if entry_delay == "next_1m_close":
        return 1, "close"
    if entry_delay == "next_3m_close":
        return 3, "close"
    if entry_delay == "next_5m_close":
        return 5, "close"
    raise ValueError(f"Unsupported entry_delay: {entry_delay}")


def _stop_target_prices(entry_price: float, side: str, variant: CalibrationVariant, spec: InstrumentSpec) -> tuple[float | None, float | None]:
    if variant.stop_model == "none":
        return None, None
    ticks = _tick_params(spec.symbol)
    stop_delta = float(ticks["stop_ticks"]) * spec.tick_size
    multiple = {"1R": 1.0, "1.5R": 1.5, "2R": 2.0}.get(variant.target_model, 1.0)
    target_delta = stop_delta * multiple
    if side == "long":
        return entry_price - stop_delta, entry_price + target_delta
    return entry_price + stop_delta, entry_price - target_delta


def _max_drawdown(trades: pd.DataFrame) -> float:
    curve = trades.sort_values("entry_time")["net_pnl"].cumsum()
    drawdowns = curve - curve.cummax()
    return float(drawdowns.min()) if not drawdowns.empty else 0.0


def _best_day_concentration(trades: pd.DataFrame, total_net: float) -> float:
    if total_net <= 0:
        return 1.0
    daily = trades.groupby("trading_session")["net_pnl"].sum()
    return float(max(daily.max(), 0.0) / total_net) if not daily.empty else 1.0


def _best_trade_concentration(trades: pd.DataFrame, total_net: float) -> float:
    if total_net <= 0 or trades.empty:
        return 1.0
    return float(max(float(trades["net_pnl"].max()), 0.0) / total_net)


def _calibration_score(row: dict[str, Any]) -> float:
    net = float(row.get("net_pnl", 0.0))
    stress = float(row.get("slippage_4_ticks_net_pnl", 0.0))
    validation = float(row.get("validation_pnl", 0.0))
    holdout = float(row.get("holdout_pnl", 0.0))
    trades = float(row.get("executable_trade_count", 0.0))
    skipped = float(row.get("skipped_event_count", 0.0))
    ambiguity = float(row.get("same_bar_stop_target_ambiguity_count", 0.0))
    drawdown = abs(float(row.get("max_drawdown", 0.0)))
    score = 0.0
    score += max(min(net / 4_000.0, 2.0), -2.0) * 18.0
    score += max(min(stress / 4_000.0, 2.0), -2.0) * 24.0
    score += max(min(validation / 1_500.0, 2.0), -2.0) * 10.0
    score += max(min(holdout / 1_500.0, 2.0), -2.0) * 14.0
    score += min(trades / 250.0, 1.0) * 10.0
    score -= min(drawdown / 3_000.0, 2.0) * 12.0
    score -= min(ambiguity / max(trades, 1.0), 1.0) * 12.0
    score -= min(skipped / max(trades + skipped, 1.0), 1.0) * 4.0
    return round(float(score), 4)


def _calibration_label(row: dict[str, Any], config: Phase8GConfig) -> str:
    if int(row["executable_trade_count"]) <= 0:
        return "too_sparse"
    if float(row["net_pnl"]) <= 0:
        return "rejected_timing_cost"
    if float(row["slippage_4_ticks_net_pnl"]) <= 0:
        return "cost_sensitive"
    if int(row["same_bar_stop_target_ambiguity_count"]) / max(int(row["executable_trade_count"]), 1) > 0.25:
        return "ambiguous_execution"
    if float(row["best_day_concentration"]) > config.concentration_limit or float(row["best_trade_concentration"]) > config.concentration_limit:
        return "concentrated"
    if float(row["validation_pnl"]) < 0 or float(row["holdout_pnl"]) < 0:
        return "split_unstable"
    return "calibration_survivor"


def _calibration_notes(row: dict[str, Any], config: Phase8GConfig) -> str:
    notes = []
    if float(row["net_pnl"]) <= 0:
        notes.append("negative net after next-step execution assumptions")
    if float(row["slippage_4_ticks_net_pnl"]) <= 0:
        notes.append("fails 4-tick slippage stress")
    if float(row["validation_pnl"]) < 0:
        notes.append("negative validation split")
    if float(row["holdout_pnl"]) < 0:
        notes.append("negative holdout split")
    if float(row["best_day_concentration"]) > config.concentration_limit:
        notes.append("one-day concentration risk")
    if float(row["best_trade_concentration"]) > config.concentration_limit:
        notes.append("one-trade concentration risk")
    if int(row["same_bar_stop_target_ambiguity_count"]) > 0:
        notes.append("same-bar stop/target ambiguity observed")
    return "; ".join(notes) if notes else "survives simple event-to-execution calibration; requires deterministic family design before deeper search"


def _calibration_id(hypothesis: dict[str, Any], entry_delay: str, variant: CalibrationVariant) -> str:
    return f"{hypothesis['hypothesis_id']}__{entry_delay}__{variant.stop_model}_{variant.target_model}_{variant.time_stop}m"


def _result_columns(include_rank: bool = False) -> list[str]:
    columns = [
        "calibration_id",
        "hypothesis_id",
        "instrument",
        "family",
        "side",
        "timeframe",
        "entry_delay",
        "stop_model",
        "target_model",
        "time_stop",
        "event_count",
        "executable_trade_count",
        "skipped_event_count",
        "gross_pnl",
        "net_pnl",
        "slippage_4_ticks_net_pnl",
        "validation_pnl",
        "holdout_pnl",
        "max_drawdown",
        "best_day_concentration",
        "best_trade_concentration",
        "same_bar_stop_target_ambiguity_count",
        "calibration_score",
        "calibration_label",
        "calibration_notes",
    ]
    if include_rank:
        return ["phase8g_rank", *columns]
    return columns
